FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /k8s-apiserver ./cmd/k8s-apiserver/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /k8s-apiserver .
EXPOSE 8443
CMD ["/root/k8s-apiserver"] 