apiVersion: v1
kind: ConfigMap
metadata:
  name: test-apiserver-config
data:
  config.yaml: |
    backend_client:
      endpoint: "localhost:9090"
      max_retries: 3
      connect_timeout: "10s"
      request_timeout: "30s"
      rate_limit: 100.0
      rate_burst: 200
      cb_max_requests: 5
      cb_interval: "60s"
      cb_timeout: "60s"
      cb_failure_threshold: 5
      cache_default_ttl: "5m"
      cache_cleanup_interval: "10m"
    
    watch:
      mode: "polling"
      streaming_enabled: false
      polling_interval: "5s"
      stream_reconnect_delay: "1s" 