/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	netguardv1beta1 "netguard-pg-backend/pkg/k8s/clientset/versioned/typed/netguard/v1beta1"

	gentype "k8s.io/client-go/gentype"
)

// fakeRuleS2Ss implements RuleS2SInterface
type fakeRuleS2Ss struct {
	*gentype.FakeClientWithList[*v1beta1.RuleS2S, *v1beta1.RuleS2SList]
	Fake *FakeNetguardV1beta1
}

func newFakeRuleS2Ss(fake *FakeNetguardV1beta1, namespace string) netguardv1beta1.RuleS2SInterface {
	return &fakeRuleS2Ss{
		gentype.NewFakeClientWithList[*v1beta1.RuleS2S, *v1beta1.RuleS2SList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("rules2ss"),
			v1beta1.SchemeGroupVersion.WithKind("RuleS2S"),
			func() *v1beta1.RuleS2S { return &v1beta1.RuleS2S{} },
			func() *v1beta1.RuleS2SList { return &v1beta1.RuleS2SList{} },
			func(dst, src *v1beta1.RuleS2SList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.RuleS2SList) []*v1beta1.RuleS2S { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.RuleS2SList, items []*v1beta1.RuleS2S) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
