/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	netguardv1beta1 "netguard-pg-backend/pkg/k8s/clientset/versioned/typed/netguard/v1beta1"

	gentype "k8s.io/client-go/gentype"
)

// fakeSvcSvcRules implements SvcSvcRuleInterface
type fakeSvcSvcRules struct {
	*gentype.FakeClientWithList[*v1beta1.SvcSvcRule, *v1beta1.SvcSvcRuleList]
	Fake *FakeNetguardV1beta1
}

func newFakeSvcSvcRules(fake *FakeNetguardV1beta1, namespace string) netguardv1beta1.SvcSvcRuleInterface {
	return &fakeSvcSvcRules{
		gentype.NewFakeClientWithList[*v1beta1.SvcSvcRule, *v1beta1.SvcSvcRuleList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("svcsvcrules"),
			v1beta1.SchemeGroupVersion.WithKind("SvcSvcRule"),
			func() *v1beta1.SvcSvcRule { return &v1beta1.SvcSvcRule{} },
			func() *v1beta1.SvcSvcRuleList { return &v1beta1.SvcSvcRuleList{} },
			func(dst, src *v1beta1.SvcSvcRuleList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.SvcSvcRuleList) []*v1beta1.SvcSvcRule { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.SvcSvcRuleList, items []*v1beta1.SvcSvcRule) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
