// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: netguard/service.proto

package netguard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetguardService_Sync_FullMethodName                             = "/netguard.v1.NetguardService/Sync"
	NetguardService_SyncStatus_FullMethodName                       = "/netguard.v1.NetguardService/SyncStatus"
	NetguardService_MarkForDeletion_FullMethodName                  = "/netguard.v1.NetguardService/MarkForDeletion"
	NetguardService_ListServices_FullMethodName                     = "/netguard.v1.NetguardService/ListServices"
	NetguardService_GetService_FullMethodName                       = "/netguard.v1.NetguardService/GetService"
	NetguardService_ListAddressGroups_FullMethodName                = "/netguard.v1.NetguardService/ListAddressGroups"
	NetguardService_GetAddressGroup_FullMethodName                  = "/netguard.v1.NetguardService/GetAddressGroup"
	NetguardService_ListAddressGroupBindings_FullMethodName         = "/netguard.v1.NetguardService/ListAddressGroupBindings"
	NetguardService_GetAddressGroupBinding_FullMethodName           = "/netguard.v1.NetguardService/GetAddressGroupBinding"
	NetguardService_ListAddressGroupPortMappings_FullMethodName     = "/netguard.v1.NetguardService/ListAddressGroupPortMappings"
	NetguardService_GetAddressGroupPortMapping_FullMethodName       = "/netguard.v1.NetguardService/GetAddressGroupPortMapping"
	NetguardService_ListAddressGroupBindingPolicies_FullMethodName  = "/netguard.v1.NetguardService/ListAddressGroupBindingPolicies"
	NetguardService_GetAddressGroupBindingPolicy_FullMethodName     = "/netguard.v1.NetguardService/GetAddressGroupBindingPolicy"
	NetguardService_ListHosts_FullMethodName                        = "/netguard.v1.NetguardService/ListHosts"
	NetguardService_GetHost_FullMethodName                          = "/netguard.v1.NetguardService/GetHost"
	NetguardService_ListHostBindings_FullMethodName                 = "/netguard.v1.NetguardService/ListHostBindings"
	NetguardService_GetHostBinding_FullMethodName                   = "/netguard.v1.NetguardService/GetHostBinding"
	NetguardService_ListNetworks_FullMethodName                     = "/netguard.v1.NetguardService/ListNetworks"
	NetguardService_GetNetwork_FullMethodName                       = "/netguard.v1.NetguardService/GetNetwork"
	NetguardService_ListNetworkBindings_FullMethodName              = "/netguard.v1.NetguardService/ListNetworkBindings"
	NetguardService_GetNetworkBinding_FullMethodName                = "/netguard.v1.NetguardService/GetNetworkBinding"
	NetguardService_ListSvcSvcRules_FullMethodName                  = "/netguard.v1.NetguardService/ListSvcSvcRules"
	NetguardService_GetSvcSvcRule_FullMethodName                    = "/netguard.v1.NetguardService/GetSvcSvcRule"
	NetguardService_ListSvcFqdnRules_FullMethodName                 = "/netguard.v1.NetguardService/ListSvcFqdnRules"
	NetguardService_GetSvcFqdnRule_FullMethodName                   = "/netguard.v1.NetguardService/GetSvcFqdnRule"
	NetguardService_ListIECidrSvcRules_FullMethodName               = "/netguard.v1.NetguardService/ListIECidrSvcRules"
	NetguardService_GetIECidrSvcRule_FullMethodName                 = "/netguard.v1.NetguardService/GetIECidrSvcRule"
	NetguardService_WatchServices_FullMethodName                    = "/netguard.v1.NetguardService/WatchServices"
	NetguardService_WatchAddressGroups_FullMethodName               = "/netguard.v1.NetguardService/WatchAddressGroups"
	NetguardService_WatchAddressGroupBindings_FullMethodName        = "/netguard.v1.NetguardService/WatchAddressGroupBindings"
	NetguardService_WatchAddressGroupPortMappings_FullMethodName    = "/netguard.v1.NetguardService/WatchAddressGroupPortMappings"
	NetguardService_WatchAddressGroupBindingPolicies_FullMethodName = "/netguard.v1.NetguardService/WatchAddressGroupBindingPolicies"
	NetguardService_WatchHosts_FullMethodName                       = "/netguard.v1.NetguardService/WatchHosts"
	NetguardService_WatchHostBindings_FullMethodName                = "/netguard.v1.NetguardService/WatchHostBindings"
	NetguardService_WatchNetworks_FullMethodName                    = "/netguard.v1.NetguardService/WatchNetworks"
	NetguardService_WatchNetworkBindings_FullMethodName             = "/netguard.v1.NetguardService/WatchNetworkBindings"
	NetguardService_WatchSvcSvcRules_FullMethodName                 = "/netguard.v1.NetguardService/WatchSvcSvcRules"
	NetguardService_WatchSvcFqdnRules_FullMethodName                = "/netguard.v1.NetguardService/WatchSvcFqdnRules"
	NetguardService_WatchIECidrSvcRules_FullMethodName              = "/netguard.v1.NetguardService/WatchIECidrSvcRules"
)

// NetguardServiceClient is the client API for NetguardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetguardServiceClient interface {
	Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SyncStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SyncStatusResp, error)
	MarkForDeletion(ctx context.Context, in *MarkForDeletionReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListServicesResp, error)
	GetService(ctx context.Context, in *GetServiceReq, opts ...grpc.CallOption) (*GetServiceResp, error)
	ListAddressGroups(ctx context.Context, in *ListAddressGroupsReq, opts ...grpc.CallOption) (*ListAddressGroupsResp, error)
	GetAddressGroup(ctx context.Context, in *GetAddressGroupReq, opts ...grpc.CallOption) (*GetAddressGroupResp, error)
	ListAddressGroupBindings(ctx context.Context, in *ListAddressGroupBindingsReq, opts ...grpc.CallOption) (*ListAddressGroupBindingsResp, error)
	GetAddressGroupBinding(ctx context.Context, in *GetAddressGroupBindingReq, opts ...grpc.CallOption) (*GetAddressGroupBindingResp, error)
	ListAddressGroupPortMappings(ctx context.Context, in *ListAddressGroupPortMappingsReq, opts ...grpc.CallOption) (*ListAddressGroupPortMappingsResp, error)
	GetAddressGroupPortMapping(ctx context.Context, in *GetAddressGroupPortMappingReq, opts ...grpc.CallOption) (*GetAddressGroupPortMappingResp, error)
	ListAddressGroupBindingPolicies(ctx context.Context, in *ListAddressGroupBindingPoliciesReq, opts ...grpc.CallOption) (*ListAddressGroupBindingPoliciesResp, error)
	GetAddressGroupBindingPolicy(ctx context.Context, in *GetAddressGroupBindingPolicyReq, opts ...grpc.CallOption) (*GetAddressGroupBindingPolicyResp, error)
	ListHosts(ctx context.Context, in *ListHostsReq, opts ...grpc.CallOption) (*ListHostsResp, error)
	GetHost(ctx context.Context, in *GetHostReq, opts ...grpc.CallOption) (*GetHostResp, error)
	ListHostBindings(ctx context.Context, in *ListHostBindingsReq, opts ...grpc.CallOption) (*ListHostBindingsResp, error)
	GetHostBinding(ctx context.Context, in *GetHostBindingReq, opts ...grpc.CallOption) (*GetHostBindingResp, error)
	ListNetworks(ctx context.Context, in *ListNetworksReq, opts ...grpc.CallOption) (*ListNetworksResp, error)
	GetNetwork(ctx context.Context, in *GetNetworkReq, opts ...grpc.CallOption) (*GetNetworkResp, error)
	ListNetworkBindings(ctx context.Context, in *ListNetworkBindingsReq, opts ...grpc.CallOption) (*ListNetworkBindingsResp, error)
	GetNetworkBinding(ctx context.Context, in *GetNetworkBindingReq, opts ...grpc.CallOption) (*GetNetworkBindingResp, error)
	ListSvcSvcRules(ctx context.Context, in *ListSvcSvcRulesReq, opts ...grpc.CallOption) (*ListSvcSvcRulesResp, error)
	GetSvcSvcRule(ctx context.Context, in *GetSvcSvcRuleReq, opts ...grpc.CallOption) (*GetSvcSvcRuleResp, error)
	ListSvcFqdnRules(ctx context.Context, in *ListSvcFqdnRulesReq, opts ...grpc.CallOption) (*ListSvcFqdnRulesResp, error)
	GetSvcFqdnRule(ctx context.Context, in *GetSvcFqdnRuleReq, opts ...grpc.CallOption) (*GetSvcFqdnRuleResp, error)
	ListIECidrSvcRules(ctx context.Context, in *ListIECidrSvcRulesReq, opts ...grpc.CallOption) (*ListIECidrSvcRulesResp, error)
	GetIECidrSvcRule(ctx context.Context, in *GetIECidrSvcRuleReq, opts ...grpc.CallOption) (*GetIECidrSvcRuleResp, error)
	WatchServices(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchAddressGroups(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchAddressGroupBindings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchAddressGroupPortMappings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchAddressGroupBindingPolicies(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchHosts(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchHostBindings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchNetworks(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchNetworkBindings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchSvcSvcRules(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchSvcFqdnRules(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	WatchIECidrSvcRules(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
}

type netguardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetguardServiceClient(cc grpc.ClientConnInterface) NetguardServiceClient {
	return &netguardServiceClient{cc}
}

func (c *netguardServiceClient) Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NetguardService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) SyncStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SyncStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStatusResp)
	err := c.cc.Invoke(ctx, NetguardService_SyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) MarkForDeletion(ctx context.Context, in *MarkForDeletionReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NetguardService_MarkForDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListServicesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResp)
	err := c.cc.Invoke(ctx, NetguardService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetService(ctx context.Context, in *GetServiceReq, opts ...grpc.CallOption) (*GetServiceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceResp)
	err := c.cc.Invoke(ctx, NetguardService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListAddressGroups(ctx context.Context, in *ListAddressGroupsReq, opts ...grpc.CallOption) (*ListAddressGroupsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressGroupsResp)
	err := c.cc.Invoke(ctx, NetguardService_ListAddressGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetAddressGroup(ctx context.Context, in *GetAddressGroupReq, opts ...grpc.CallOption) (*GetAddressGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAddressGroupResp)
	err := c.cc.Invoke(ctx, NetguardService_GetAddressGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListAddressGroupBindings(ctx context.Context, in *ListAddressGroupBindingsReq, opts ...grpc.CallOption) (*ListAddressGroupBindingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressGroupBindingsResp)
	err := c.cc.Invoke(ctx, NetguardService_ListAddressGroupBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetAddressGroupBinding(ctx context.Context, in *GetAddressGroupBindingReq, opts ...grpc.CallOption) (*GetAddressGroupBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAddressGroupBindingResp)
	err := c.cc.Invoke(ctx, NetguardService_GetAddressGroupBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListAddressGroupPortMappings(ctx context.Context, in *ListAddressGroupPortMappingsReq, opts ...grpc.CallOption) (*ListAddressGroupPortMappingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressGroupPortMappingsResp)
	err := c.cc.Invoke(ctx, NetguardService_ListAddressGroupPortMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetAddressGroupPortMapping(ctx context.Context, in *GetAddressGroupPortMappingReq, opts ...grpc.CallOption) (*GetAddressGroupPortMappingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAddressGroupPortMappingResp)
	err := c.cc.Invoke(ctx, NetguardService_GetAddressGroupPortMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListAddressGroupBindingPolicies(ctx context.Context, in *ListAddressGroupBindingPoliciesReq, opts ...grpc.CallOption) (*ListAddressGroupBindingPoliciesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressGroupBindingPoliciesResp)
	err := c.cc.Invoke(ctx, NetguardService_ListAddressGroupBindingPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetAddressGroupBindingPolicy(ctx context.Context, in *GetAddressGroupBindingPolicyReq, opts ...grpc.CallOption) (*GetAddressGroupBindingPolicyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAddressGroupBindingPolicyResp)
	err := c.cc.Invoke(ctx, NetguardService_GetAddressGroupBindingPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListHosts(ctx context.Context, in *ListHostsReq, opts ...grpc.CallOption) (*ListHostsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostsResp)
	err := c.cc.Invoke(ctx, NetguardService_ListHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetHost(ctx context.Context, in *GetHostReq, opts ...grpc.CallOption) (*GetHostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostResp)
	err := c.cc.Invoke(ctx, NetguardService_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListHostBindings(ctx context.Context, in *ListHostBindingsReq, opts ...grpc.CallOption) (*ListHostBindingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostBindingsResp)
	err := c.cc.Invoke(ctx, NetguardService_ListHostBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetHostBinding(ctx context.Context, in *GetHostBindingReq, opts ...grpc.CallOption) (*GetHostBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostBindingResp)
	err := c.cc.Invoke(ctx, NetguardService_GetHostBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListNetworks(ctx context.Context, in *ListNetworksReq, opts ...grpc.CallOption) (*ListNetworksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResp)
	err := c.cc.Invoke(ctx, NetguardService_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetNetwork(ctx context.Context, in *GetNetworkReq, opts ...grpc.CallOption) (*GetNetworkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkResp)
	err := c.cc.Invoke(ctx, NetguardService_GetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListNetworkBindings(ctx context.Context, in *ListNetworkBindingsReq, opts ...grpc.CallOption) (*ListNetworkBindingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworkBindingsResp)
	err := c.cc.Invoke(ctx, NetguardService_ListNetworkBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetNetworkBinding(ctx context.Context, in *GetNetworkBindingReq, opts ...grpc.CallOption) (*GetNetworkBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkBindingResp)
	err := c.cc.Invoke(ctx, NetguardService_GetNetworkBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListSvcSvcRules(ctx context.Context, in *ListSvcSvcRulesReq, opts ...grpc.CallOption) (*ListSvcSvcRulesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSvcSvcRulesResp)
	err := c.cc.Invoke(ctx, NetguardService_ListSvcSvcRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetSvcSvcRule(ctx context.Context, in *GetSvcSvcRuleReq, opts ...grpc.CallOption) (*GetSvcSvcRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSvcSvcRuleResp)
	err := c.cc.Invoke(ctx, NetguardService_GetSvcSvcRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListSvcFqdnRules(ctx context.Context, in *ListSvcFqdnRulesReq, opts ...grpc.CallOption) (*ListSvcFqdnRulesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSvcFqdnRulesResp)
	err := c.cc.Invoke(ctx, NetguardService_ListSvcFqdnRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetSvcFqdnRule(ctx context.Context, in *GetSvcFqdnRuleReq, opts ...grpc.CallOption) (*GetSvcFqdnRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSvcFqdnRuleResp)
	err := c.cc.Invoke(ctx, NetguardService_GetSvcFqdnRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) ListIECidrSvcRules(ctx context.Context, in *ListIECidrSvcRulesReq, opts ...grpc.CallOption) (*ListIECidrSvcRulesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIECidrSvcRulesResp)
	err := c.cc.Invoke(ctx, NetguardService_ListIECidrSvcRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) GetIECidrSvcRule(ctx context.Context, in *GetIECidrSvcRuleReq, opts ...grpc.CallOption) (*GetIECidrSvcRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIECidrSvcRuleResp)
	err := c.cc.Invoke(ctx, NetguardService_GetIECidrSvcRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netguardServiceClient) WatchServices(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[0], NetguardService_WatchServices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchServicesClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchAddressGroups(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[1], NetguardService_WatchAddressGroups_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupsClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchAddressGroupBindings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[2], NetguardService_WatchAddressGroupBindings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupBindingsClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchAddressGroupPortMappings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[3], NetguardService_WatchAddressGroupPortMappings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupPortMappingsClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchAddressGroupBindingPolicies(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[4], NetguardService_WatchAddressGroupBindingPolicies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupBindingPoliciesClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchHosts(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[5], NetguardService_WatchHosts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchHostsClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchHostBindings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[6], NetguardService_WatchHostBindings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchHostBindingsClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchNetworks(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[7], NetguardService_WatchNetworks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchNetworksClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchNetworkBindings(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[8], NetguardService_WatchNetworkBindings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchNetworkBindingsClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchSvcSvcRules(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[9], NetguardService_WatchSvcSvcRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchSvcSvcRulesClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchSvcFqdnRules(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[10], NetguardService_WatchSvcFqdnRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchSvcFqdnRulesClient = grpc.ServerStreamingClient[WatchEvent]

func (c *netguardServiceClient) WatchIECidrSvcRules(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetguardService_ServiceDesc.Streams[11], NetguardService_WatchIECidrSvcRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchIECidrSvcRulesClient = grpc.ServerStreamingClient[WatchEvent]

// NetguardServiceServer is the server API for NetguardService service.
// All implementations must embed UnimplementedNetguardServiceServer
// for forward compatibility.
type NetguardServiceServer interface {
	Sync(context.Context, *SyncReq) (*emptypb.Empty, error)
	SyncStatus(context.Context, *emptypb.Empty) (*SyncStatusResp, error)
	MarkForDeletion(context.Context, *MarkForDeletionReq) (*emptypb.Empty, error)
	ListServices(context.Context, *ListServicesReq) (*ListServicesResp, error)
	GetService(context.Context, *GetServiceReq) (*GetServiceResp, error)
	ListAddressGroups(context.Context, *ListAddressGroupsReq) (*ListAddressGroupsResp, error)
	GetAddressGroup(context.Context, *GetAddressGroupReq) (*GetAddressGroupResp, error)
	ListAddressGroupBindings(context.Context, *ListAddressGroupBindingsReq) (*ListAddressGroupBindingsResp, error)
	GetAddressGroupBinding(context.Context, *GetAddressGroupBindingReq) (*GetAddressGroupBindingResp, error)
	ListAddressGroupPortMappings(context.Context, *ListAddressGroupPortMappingsReq) (*ListAddressGroupPortMappingsResp, error)
	GetAddressGroupPortMapping(context.Context, *GetAddressGroupPortMappingReq) (*GetAddressGroupPortMappingResp, error)
	ListAddressGroupBindingPolicies(context.Context, *ListAddressGroupBindingPoliciesReq) (*ListAddressGroupBindingPoliciesResp, error)
	GetAddressGroupBindingPolicy(context.Context, *GetAddressGroupBindingPolicyReq) (*GetAddressGroupBindingPolicyResp, error)
	ListHosts(context.Context, *ListHostsReq) (*ListHostsResp, error)
	GetHost(context.Context, *GetHostReq) (*GetHostResp, error)
	ListHostBindings(context.Context, *ListHostBindingsReq) (*ListHostBindingsResp, error)
	GetHostBinding(context.Context, *GetHostBindingReq) (*GetHostBindingResp, error)
	ListNetworks(context.Context, *ListNetworksReq) (*ListNetworksResp, error)
	GetNetwork(context.Context, *GetNetworkReq) (*GetNetworkResp, error)
	ListNetworkBindings(context.Context, *ListNetworkBindingsReq) (*ListNetworkBindingsResp, error)
	GetNetworkBinding(context.Context, *GetNetworkBindingReq) (*GetNetworkBindingResp, error)
	ListSvcSvcRules(context.Context, *ListSvcSvcRulesReq) (*ListSvcSvcRulesResp, error)
	GetSvcSvcRule(context.Context, *GetSvcSvcRuleReq) (*GetSvcSvcRuleResp, error)
	ListSvcFqdnRules(context.Context, *ListSvcFqdnRulesReq) (*ListSvcFqdnRulesResp, error)
	GetSvcFqdnRule(context.Context, *GetSvcFqdnRuleReq) (*GetSvcFqdnRuleResp, error)
	ListIECidrSvcRules(context.Context, *ListIECidrSvcRulesReq) (*ListIECidrSvcRulesResp, error)
	GetIECidrSvcRule(context.Context, *GetIECidrSvcRuleReq) (*GetIECidrSvcRuleResp, error)
	WatchServices(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchAddressGroups(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchAddressGroupBindings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchAddressGroupPortMappings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchAddressGroupBindingPolicies(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchHosts(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchHostBindings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchNetworks(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchNetworkBindings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchSvcSvcRules(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchSvcFqdnRules(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	WatchIECidrSvcRules(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	mustEmbedUnimplementedNetguardServiceServer()
}

// UnimplementedNetguardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetguardServiceServer struct{}

func (UnimplementedNetguardServiceServer) Sync(context.Context, *SyncReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedNetguardServiceServer) SyncStatus(context.Context, *emptypb.Empty) (*SyncStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncStatus not implemented")
}
func (UnimplementedNetguardServiceServer) MarkForDeletion(context.Context, *MarkForDeletionReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkForDeletion not implemented")
}
func (UnimplementedNetguardServiceServer) ListServices(context.Context, *ListServicesReq) (*ListServicesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedNetguardServiceServer) GetService(context.Context, *GetServiceReq) (*GetServiceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedNetguardServiceServer) ListAddressGroups(context.Context, *ListAddressGroupsReq) (*ListAddressGroupsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAddressGroups not implemented")
}
func (UnimplementedNetguardServiceServer) GetAddressGroup(context.Context, *GetAddressGroupReq) (*GetAddressGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressGroup not implemented")
}
func (UnimplementedNetguardServiceServer) ListAddressGroupBindings(context.Context, *ListAddressGroupBindingsReq) (*ListAddressGroupBindingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAddressGroupBindings not implemented")
}
func (UnimplementedNetguardServiceServer) GetAddressGroupBinding(context.Context, *GetAddressGroupBindingReq) (*GetAddressGroupBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressGroupBinding not implemented")
}
func (UnimplementedNetguardServiceServer) ListAddressGroupPortMappings(context.Context, *ListAddressGroupPortMappingsReq) (*ListAddressGroupPortMappingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAddressGroupPortMappings not implemented")
}
func (UnimplementedNetguardServiceServer) GetAddressGroupPortMapping(context.Context, *GetAddressGroupPortMappingReq) (*GetAddressGroupPortMappingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressGroupPortMapping not implemented")
}
func (UnimplementedNetguardServiceServer) ListAddressGroupBindingPolicies(context.Context, *ListAddressGroupBindingPoliciesReq) (*ListAddressGroupBindingPoliciesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAddressGroupBindingPolicies not implemented")
}
func (UnimplementedNetguardServiceServer) GetAddressGroupBindingPolicy(context.Context, *GetAddressGroupBindingPolicyReq) (*GetAddressGroupBindingPolicyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressGroupBindingPolicy not implemented")
}
func (UnimplementedNetguardServiceServer) ListHosts(context.Context, *ListHostsReq) (*ListHostsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedNetguardServiceServer) GetHost(context.Context, *GetHostReq) (*GetHostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedNetguardServiceServer) ListHostBindings(context.Context, *ListHostBindingsReq) (*ListHostBindingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHostBindings not implemented")
}
func (UnimplementedNetguardServiceServer) GetHostBinding(context.Context, *GetHostBindingReq) (*GetHostBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostBinding not implemented")
}
func (UnimplementedNetguardServiceServer) ListNetworks(context.Context, *ListNetworksReq) (*ListNetworksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedNetguardServiceServer) GetNetwork(context.Context, *GetNetworkReq) (*GetNetworkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetwork not implemented")
}
func (UnimplementedNetguardServiceServer) ListNetworkBindings(context.Context, *ListNetworkBindingsReq) (*ListNetworkBindingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNetworkBindings not implemented")
}
func (UnimplementedNetguardServiceServer) GetNetworkBinding(context.Context, *GetNetworkBindingReq) (*GetNetworkBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkBinding not implemented")
}
func (UnimplementedNetguardServiceServer) ListSvcSvcRules(context.Context, *ListSvcSvcRulesReq) (*ListSvcSvcRulesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSvcSvcRules not implemented")
}
func (UnimplementedNetguardServiceServer) GetSvcSvcRule(context.Context, *GetSvcSvcRuleReq) (*GetSvcSvcRuleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSvcSvcRule not implemented")
}
func (UnimplementedNetguardServiceServer) ListSvcFqdnRules(context.Context, *ListSvcFqdnRulesReq) (*ListSvcFqdnRulesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSvcFqdnRules not implemented")
}
func (UnimplementedNetguardServiceServer) GetSvcFqdnRule(context.Context, *GetSvcFqdnRuleReq) (*GetSvcFqdnRuleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSvcFqdnRule not implemented")
}
func (UnimplementedNetguardServiceServer) ListIECidrSvcRules(context.Context, *ListIECidrSvcRulesReq) (*ListIECidrSvcRulesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIECidrSvcRules not implemented")
}
func (UnimplementedNetguardServiceServer) GetIECidrSvcRule(context.Context, *GetIECidrSvcRuleReq) (*GetIECidrSvcRuleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIECidrSvcRule not implemented")
}
func (UnimplementedNetguardServiceServer) WatchServices(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchServices not implemented")
}
func (UnimplementedNetguardServiceServer) WatchAddressGroups(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchAddressGroups not implemented")
}
func (UnimplementedNetguardServiceServer) WatchAddressGroupBindings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchAddressGroupBindings not implemented")
}
func (UnimplementedNetguardServiceServer) WatchAddressGroupPortMappings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchAddressGroupPortMappings not implemented")
}
func (UnimplementedNetguardServiceServer) WatchAddressGroupBindingPolicies(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchAddressGroupBindingPolicies not implemented")
}
func (UnimplementedNetguardServiceServer) WatchHosts(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchHosts not implemented")
}
func (UnimplementedNetguardServiceServer) WatchHostBindings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchHostBindings not implemented")
}
func (UnimplementedNetguardServiceServer) WatchNetworks(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchNetworks not implemented")
}
func (UnimplementedNetguardServiceServer) WatchNetworkBindings(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchNetworkBindings not implemented")
}
func (UnimplementedNetguardServiceServer) WatchSvcSvcRules(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchSvcSvcRules not implemented")
}
func (UnimplementedNetguardServiceServer) WatchSvcFqdnRules(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchSvcFqdnRules not implemented")
}
func (UnimplementedNetguardServiceServer) WatchIECidrSvcRules(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchIECidrSvcRules not implemented")
}
func (UnimplementedNetguardServiceServer) mustEmbedUnimplementedNetguardServiceServer() {}
func (UnimplementedNetguardServiceServer) testEmbeddedByValue()                         {}

// UnsafeNetguardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetguardServiceServer will
// result in compilation errors.
type UnsafeNetguardServiceServer interface {
	mustEmbedUnimplementedNetguardServiceServer()
}

func RegisterNetguardServiceServer(s grpc.ServiceRegistrar, srv NetguardServiceServer) {
	// If the following call pancis, it indicates UnimplementedNetguardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetguardService_ServiceDesc, srv)
}

func _NetguardService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).Sync(ctx, req.(*SyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_SyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).SyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_SyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).SyncStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_MarkForDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkForDeletionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).MarkForDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_MarkForDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).MarkForDeletion(ctx, req.(*MarkForDeletionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListServices(ctx, req.(*ListServicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetService(ctx, req.(*GetServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListAddressGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListAddressGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListAddressGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListAddressGroups(ctx, req.(*ListAddressGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetAddressGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetAddressGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetAddressGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetAddressGroup(ctx, req.(*GetAddressGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListAddressGroupBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressGroupBindingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListAddressGroupBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListAddressGroupBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListAddressGroupBindings(ctx, req.(*ListAddressGroupBindingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetAddressGroupBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressGroupBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetAddressGroupBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetAddressGroupBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetAddressGroupBinding(ctx, req.(*GetAddressGroupBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListAddressGroupPortMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressGroupPortMappingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListAddressGroupPortMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListAddressGroupPortMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListAddressGroupPortMappings(ctx, req.(*ListAddressGroupPortMappingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetAddressGroupPortMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressGroupPortMappingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetAddressGroupPortMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetAddressGroupPortMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetAddressGroupPortMapping(ctx, req.(*GetAddressGroupPortMappingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListAddressGroupBindingPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressGroupBindingPoliciesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListAddressGroupBindingPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListAddressGroupBindingPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListAddressGroupBindingPolicies(ctx, req.(*ListAddressGroupBindingPoliciesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetAddressGroupBindingPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressGroupBindingPolicyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetAddressGroupBindingPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetAddressGroupBindingPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetAddressGroupBindingPolicy(ctx, req.(*GetAddressGroupBindingPolicyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListHosts(ctx, req.(*ListHostsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetHost(ctx, req.(*GetHostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListHostBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostBindingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListHostBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListHostBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListHostBindings(ctx, req.(*ListHostBindingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetHostBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetHostBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetHostBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetHostBinding(ctx, req.(*GetHostBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListNetworks(ctx, req.(*ListNetworksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetNetwork(ctx, req.(*GetNetworkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListNetworkBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkBindingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListNetworkBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListNetworkBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListNetworkBindings(ctx, req.(*ListNetworkBindingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetNetworkBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetNetworkBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetNetworkBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetNetworkBinding(ctx, req.(*GetNetworkBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListSvcSvcRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSvcSvcRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListSvcSvcRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListSvcSvcRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListSvcSvcRules(ctx, req.(*ListSvcSvcRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetSvcSvcRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSvcSvcRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetSvcSvcRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetSvcSvcRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetSvcSvcRule(ctx, req.(*GetSvcSvcRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListSvcFqdnRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSvcFqdnRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListSvcFqdnRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListSvcFqdnRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListSvcFqdnRules(ctx, req.(*ListSvcFqdnRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetSvcFqdnRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSvcFqdnRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetSvcFqdnRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetSvcFqdnRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetSvcFqdnRule(ctx, req.(*GetSvcFqdnRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_ListIECidrSvcRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIECidrSvcRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).ListIECidrSvcRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_ListIECidrSvcRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).ListIECidrSvcRules(ctx, req.(*ListIECidrSvcRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_GetIECidrSvcRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIECidrSvcRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetguardServiceServer).GetIECidrSvcRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetguardService_GetIECidrSvcRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetguardServiceServer).GetIECidrSvcRule(ctx, req.(*GetIECidrSvcRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetguardService_WatchServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchServices(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchServicesServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchAddressGroups_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchAddressGroups(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupsServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchAddressGroupBindings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchAddressGroupBindings(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupBindingsServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchAddressGroupPortMappings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchAddressGroupPortMappings(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupPortMappingsServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchAddressGroupBindingPolicies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchAddressGroupBindingPolicies(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchAddressGroupBindingPoliciesServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchHosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchHosts(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchHostsServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchHostBindings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchHostBindings(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchHostBindingsServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchNetworks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchNetworks(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchNetworksServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchNetworkBindings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchNetworkBindings(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchNetworkBindingsServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchSvcSvcRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchSvcSvcRules(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchSvcSvcRulesServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchSvcFqdnRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchSvcFqdnRules(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchSvcFqdnRulesServer = grpc.ServerStreamingServer[WatchEvent]

func _NetguardService_WatchIECidrSvcRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetguardServiceServer).WatchIECidrSvcRules(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetguardService_WatchIECidrSvcRulesServer = grpc.ServerStreamingServer[WatchEvent]

// NetguardService_ServiceDesc is the grpc.ServiceDesc for NetguardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetguardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netguard.v1.NetguardService",
	HandlerType: (*NetguardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _NetguardService_Sync_Handler,
		},
		{
			MethodName: "SyncStatus",
			Handler:    _NetguardService_SyncStatus_Handler,
		},
		{
			MethodName: "MarkForDeletion",
			Handler:    _NetguardService_MarkForDeletion_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _NetguardService_ListServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _NetguardService_GetService_Handler,
		},
		{
			MethodName: "ListAddressGroups",
			Handler:    _NetguardService_ListAddressGroups_Handler,
		},
		{
			MethodName: "GetAddressGroup",
			Handler:    _NetguardService_GetAddressGroup_Handler,
		},
		{
			MethodName: "ListAddressGroupBindings",
			Handler:    _NetguardService_ListAddressGroupBindings_Handler,
		},
		{
			MethodName: "GetAddressGroupBinding",
			Handler:    _NetguardService_GetAddressGroupBinding_Handler,
		},
		{
			MethodName: "ListAddressGroupPortMappings",
			Handler:    _NetguardService_ListAddressGroupPortMappings_Handler,
		},
		{
			MethodName: "GetAddressGroupPortMapping",
			Handler:    _NetguardService_GetAddressGroupPortMapping_Handler,
		},
		{
			MethodName: "ListAddressGroupBindingPolicies",
			Handler:    _NetguardService_ListAddressGroupBindingPolicies_Handler,
		},
		{
			MethodName: "GetAddressGroupBindingPolicy",
			Handler:    _NetguardService_GetAddressGroupBindingPolicy_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _NetguardService_ListHosts_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _NetguardService_GetHost_Handler,
		},
		{
			MethodName: "ListHostBindings",
			Handler:    _NetguardService_ListHostBindings_Handler,
		},
		{
			MethodName: "GetHostBinding",
			Handler:    _NetguardService_GetHostBinding_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _NetguardService_ListNetworks_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _NetguardService_GetNetwork_Handler,
		},
		{
			MethodName: "ListNetworkBindings",
			Handler:    _NetguardService_ListNetworkBindings_Handler,
		},
		{
			MethodName: "GetNetworkBinding",
			Handler:    _NetguardService_GetNetworkBinding_Handler,
		},
		{
			MethodName: "ListSvcSvcRules",
			Handler:    _NetguardService_ListSvcSvcRules_Handler,
		},
		{
			MethodName: "GetSvcSvcRule",
			Handler:    _NetguardService_GetSvcSvcRule_Handler,
		},
		{
			MethodName: "ListSvcFqdnRules",
			Handler:    _NetguardService_ListSvcFqdnRules_Handler,
		},
		{
			MethodName: "GetSvcFqdnRule",
			Handler:    _NetguardService_GetSvcFqdnRule_Handler,
		},
		{
			MethodName: "ListIECidrSvcRules",
			Handler:    _NetguardService_ListIECidrSvcRules_Handler,
		},
		{
			MethodName: "GetIECidrSvcRule",
			Handler:    _NetguardService_GetIECidrSvcRule_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchServices",
			Handler:       _NetguardService_WatchServices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAddressGroups",
			Handler:       _NetguardService_WatchAddressGroups_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAddressGroupBindings",
			Handler:       _NetguardService_WatchAddressGroupBindings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAddressGroupPortMappings",
			Handler:       _NetguardService_WatchAddressGroupPortMappings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAddressGroupBindingPolicies",
			Handler:       _NetguardService_WatchAddressGroupBindingPolicies_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchHosts",
			Handler:       _NetguardService_WatchHosts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchHostBindings",
			Handler:       _NetguardService_WatchHostBindings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchNetworks",
			Handler:       _NetguardService_WatchNetworks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchNetworkBindings",
			Handler:       _NetguardService_WatchNetworkBindings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchSvcSvcRules",
			Handler:       _NetguardService_WatchSvcSvcRules_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchSvcFqdnRules",
			Handler:       _NetguardService_WatchSvcFqdnRules_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchIECidrSvcRules",
			Handler:       _NetguardService_WatchIECidrSvcRules_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "netguard/service.proto",
}
