/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	scheme "netguard-pg-backend/pkg/k8s/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AddressGroupBindingsGetter has a method to return a AddressGroupBindingInterface.
// A group's client should implement this interface.
type AddressGroupBindingsGetter interface {
	AddressGroupBindings(namespace string) AddressGroupBindingInterface
}

// AddressGroupBindingInterface has methods to work with AddressGroupBinding resources.
type AddressGroupBindingInterface interface {
	Create(ctx context.Context, addressGroupBinding *netguardv1beta1.AddressGroupBinding, opts v1.CreateOptions) (*netguardv1beta1.AddressGroupBinding, error)
	Update(ctx context.Context, addressGroupBinding *netguardv1beta1.AddressGroupBinding, opts v1.UpdateOptions) (*netguardv1beta1.AddressGroupBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, addressGroupBinding *netguardv1beta1.AddressGroupBinding, opts v1.UpdateOptions) (*netguardv1beta1.AddressGroupBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netguardv1beta1.AddressGroupBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*netguardv1beta1.AddressGroupBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netguardv1beta1.AddressGroupBinding, err error)
	AddressGroupBindingExpansion
}

// addressGroupBindings implements AddressGroupBindingInterface
type addressGroupBindings struct {
	*gentype.ClientWithList[*netguardv1beta1.AddressGroupBinding, *netguardv1beta1.AddressGroupBindingList]
}

// newAddressGroupBindings returns a AddressGroupBindings
func newAddressGroupBindings(c *NetguardV1beta1Client, namespace string) *addressGroupBindings {
	return &addressGroupBindings{
		gentype.NewClientWithList[*netguardv1beta1.AddressGroupBinding, *netguardv1beta1.AddressGroupBindingList](
			"addressgroupbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netguardv1beta1.AddressGroupBinding { return &netguardv1beta1.AddressGroupBinding{} },
			func() *netguardv1beta1.AddressGroupBindingList { return &netguardv1beta1.AddressGroupBindingList{} },
		),
	}
}
