/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	scheme "netguard-pg-backend/pkg/k8s/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetworkBindingsGetter has a method to return a NetworkBindingInterface.
// A group's client should implement this interface.
type NetworkBindingsGetter interface {
	NetworkBindings(namespace string) NetworkBindingInterface
}

// NetworkBindingInterface has methods to work with NetworkBinding resources.
type NetworkBindingInterface interface {
	Create(ctx context.Context, networkBinding *netguardv1beta1.NetworkBinding, opts v1.CreateOptions) (*netguardv1beta1.NetworkBinding, error)
	Update(ctx context.Context, networkBinding *netguardv1beta1.NetworkBinding, opts v1.UpdateOptions) (*netguardv1beta1.NetworkBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, networkBinding *netguardv1beta1.NetworkBinding, opts v1.UpdateOptions) (*netguardv1beta1.NetworkBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netguardv1beta1.NetworkBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*netguardv1beta1.NetworkBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netguardv1beta1.NetworkBinding, err error)
	NetworkBindingExpansion
}

// networkBindings implements NetworkBindingInterface
type networkBindings struct {
	*gentype.ClientWithList[*netguardv1beta1.NetworkBinding, *netguardv1beta1.NetworkBindingList]
}

// newNetworkBindings returns a NetworkBindings
func newNetworkBindings(c *NetguardV1beta1Client, namespace string) *networkBindings {
	return &networkBindings{
		gentype.NewClientWithList[*netguardv1beta1.NetworkBinding, *netguardv1beta1.NetworkBindingList](
			"networkbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netguardv1beta1.NetworkBinding { return &netguardv1beta1.NetworkBinding{} },
			func() *netguardv1beta1.NetworkBindingList { return &netguardv1beta1.NetworkBindingList{} },
		),
	}
}
