/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	scheme "netguard-pg-backend/pkg/k8s/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceAliasesGetter has a method to return a ServiceAliasInterface.
// A group's client should implement this interface.
type ServiceAliasesGetter interface {
	ServiceAliases(namespace string) ServiceAliasInterface
}

// ServiceAliasInterface has methods to work with ServiceAlias resources.
type ServiceAliasInterface interface {
	Create(ctx context.Context, serviceAlias *netguardv1beta1.ServiceAlias, opts v1.CreateOptions) (*netguardv1beta1.ServiceAlias, error)
	Update(ctx context.Context, serviceAlias *netguardv1beta1.ServiceAlias, opts v1.UpdateOptions) (*netguardv1beta1.ServiceAlias, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceAlias *netguardv1beta1.ServiceAlias, opts v1.UpdateOptions) (*netguardv1beta1.ServiceAlias, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netguardv1beta1.ServiceAlias, error)
	List(ctx context.Context, opts v1.ListOptions) (*netguardv1beta1.ServiceAliasList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netguardv1beta1.ServiceAlias, err error)
	ServiceAliasExpansion
}

// serviceAliases implements ServiceAliasInterface
type serviceAliases struct {
	*gentype.ClientWithList[*netguardv1beta1.ServiceAlias, *netguardv1beta1.ServiceAliasList]
}

// newServiceAliases returns a ServiceAliases
func newServiceAliases(c *NetguardV1beta1Client, namespace string) *serviceAliases {
	return &serviceAliases{
		gentype.NewClientWithList[*netguardv1beta1.ServiceAlias, *netguardv1beta1.ServiceAliasList](
			"servicealiases",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netguardv1beta1.ServiceAlias { return &netguardv1beta1.ServiceAlias{} },
			func() *netguardv1beta1.ServiceAliasList { return &netguardv1beta1.ServiceAliasList{} },
		),
	}
}
