/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	scheme "netguard-pg-backend/pkg/k8s/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SvcFqdnRulesGetter has a method to return a SvcFqdnRuleInterface.
// A group's client should implement this interface.
type SvcFqdnRulesGetter interface {
	SvcFqdnRules(namespace string) SvcFqdnRuleInterface
}

// SvcFqdnRuleInterface has methods to work with SvcFqdnRule resources.
type SvcFqdnRuleInterface interface {
	Create(ctx context.Context, svcFqdnRule *netguardv1beta1.SvcFqdnRule, opts v1.CreateOptions) (*netguardv1beta1.SvcFqdnRule, error)
	Update(ctx context.Context, svcFqdnRule *netguardv1beta1.SvcFqdnRule, opts v1.UpdateOptions) (*netguardv1beta1.SvcFqdnRule, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, svcFqdnRule *netguardv1beta1.SvcFqdnRule, opts v1.UpdateOptions) (*netguardv1beta1.SvcFqdnRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*netguardv1beta1.SvcFqdnRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*netguardv1beta1.SvcFqdnRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *netguardv1beta1.SvcFqdnRule, err error)
	SvcFqdnRuleExpansion
}

// svcFqdnRules implements SvcFqdnRuleInterface
type svcFqdnRules struct {
	*gentype.ClientWithList[*netguardv1beta1.SvcFqdnRule, *netguardv1beta1.SvcFqdnRuleList]
}

// newSvcFqdnRules returns a SvcFqdnRules
func newSvcFqdnRules(c *NetguardV1beta1Client, namespace string) *svcFqdnRules {
	return &svcFqdnRules{
		gentype.NewClientWithList[*netguardv1beta1.SvcFqdnRule, *netguardv1beta1.SvcFqdnRuleList](
			"svcfqdnrules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *netguardv1beta1.SvcFqdnRule { return &netguardv1beta1.SvcFqdnRule{} },
			func() *netguardv1beta1.SvcFqdnRuleList { return &netguardv1beta1.SvcFqdnRuleList{} },
		),
	}
}
