/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	apisnetguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	versioned "netguard-pg-backend/pkg/k8s/clientset/versioned"
	internalinterfaces "netguard-pg-backend/pkg/k8s/informers/externalversions/internalinterfaces"
	netguardv1beta1 "netguard-pg-backend/pkg/k8s/listers/netguard/v1beta1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AddressGroupPortMappingInformer provides access to a shared informer and lister for
// AddressGroupPortMappings.
type AddressGroupPortMappingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() netguardv1beta1.AddressGroupPortMappingLister
}

type addressGroupPortMappingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAddressGroupPortMappingInformer constructs a new informer for AddressGroupPortMapping type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAddressGroupPortMappingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAddressGroupPortMappingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAddressGroupPortMappingInformer constructs a new informer for AddressGroupPortMapping type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAddressGroupPortMappingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().AddressGroupPortMappings(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().AddressGroupPortMappings(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().AddressGroupPortMappings(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().AddressGroupPortMappings(namespace).Watch(ctx, options)
			},
		},
		&apisnetguardv1beta1.AddressGroupPortMapping{},
		resyncPeriod,
		indexers,
	)
}

func (f *addressGroupPortMappingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAddressGroupPortMappingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *addressGroupPortMappingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisnetguardv1beta1.AddressGroupPortMapping{}, f.defaultInformer)
}

func (f *addressGroupPortMappingInformer) Lister() netguardv1beta1.AddressGroupPortMappingLister {
	return netguardv1beta1.NewAddressGroupPortMappingLister(f.Informer().GetIndexer())
}
