/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	apisnetguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	versioned "netguard-pg-backend/pkg/k8s/clientset/versioned"
	internalinterfaces "netguard-pg-backend/pkg/k8s/informers/externalversions/internalinterfaces"
	netguardv1beta1 "netguard-pg-backend/pkg/k8s/listers/netguard/v1beta1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IEAgAgRuleInformer provides access to a shared informer and lister for
// IEAgAgRules.
type IEAgAgRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() netguardv1beta1.IEAgAgRuleLister
}

type iEAgAgRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIEAgAgRuleInformer constructs a new informer for IEAgAgRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIEAgAgRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIEAgAgRuleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIEAgAgRuleInformer constructs a new informer for IEAgAgRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIEAgAgRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().IEAgAgRules(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().IEAgAgRules(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().IEAgAgRules(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetguardV1beta1().IEAgAgRules(namespace).Watch(ctx, options)
			},
		},
		&apisnetguardv1beta1.IEAgAgRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *iEAgAgRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIEAgAgRuleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iEAgAgRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisnetguardv1beta1.IEAgAgRule{}, f.defaultInformer)
}

func (f *iEAgAgRuleInformer) Lister() netguardv1beta1.IEAgAgRuleLister {
	return netguardv1beta1.NewIEAgAgRuleLister(f.Informer().GetIndexer())
}
