//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package svcsvc_rule

import (
	"netguard-pg-backend/internal/domain/models"
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	"netguard-pg-backend/internal/k8s/registry/base"
)

// NewStatusREST creates a status subresource for SvcSvcRule that supports condition updates.
// This allows the backend condition processing to persist status.conditions to Kubernetes objects.
func NewStatusREST(store *SvcSvcRuleStorage) *base.StatusREST[*netguardv1beta1.SvcSvcRule, *models.SvcSvcRule] {
	return base.NewStatusREST[*netguardv1beta1.SvcSvcRule, *models.SvcSvcRule](
		store.BaseStorage,
	)
}
