/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AddressGroupBindingLister helps list AddressGroupBindings.
// All objects returned here must be treated as read-only.
type AddressGroupBindingLister interface {
	// List lists all AddressGroupBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.AddressGroupBinding, err error)
	// AddressGroupBindings returns an object that can list and get AddressGroupBindings.
	AddressGroupBindings(namespace string) AddressGroupBindingNamespaceLister
	AddressGroupBindingListerExpansion
}

// addressGroupBindingLister implements the AddressGroupBindingLister interface.
type addressGroupBindingLister struct {
	listers.ResourceIndexer[*netguardv1beta1.AddressGroupBinding]
}

// NewAddressGroupBindingLister returns a new AddressGroupBindingLister.
func NewAddressGroupBindingLister(indexer cache.Indexer) AddressGroupBindingLister {
	return &addressGroupBindingLister{listers.New[*netguardv1beta1.AddressGroupBinding](indexer, netguardv1beta1.Resource("addressgroupbinding"))}
}

// AddressGroupBindings returns an object that can list and get AddressGroupBindings.
func (s *addressGroupBindingLister) AddressGroupBindings(namespace string) AddressGroupBindingNamespaceLister {
	return addressGroupBindingNamespaceLister{listers.NewNamespaced[*netguardv1beta1.AddressGroupBinding](s.ResourceIndexer, namespace)}
}

// AddressGroupBindingNamespaceLister helps list and get AddressGroupBindings.
// All objects returned here must be treated as read-only.
type AddressGroupBindingNamespaceLister interface {
	// List lists all AddressGroupBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.AddressGroupBinding, err error)
	// Get retrieves the AddressGroupBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netguardv1beta1.AddressGroupBinding, error)
	AddressGroupBindingNamespaceListerExpansion
}

// addressGroupBindingNamespaceLister implements the AddressGroupBindingNamespaceLister
// interface.
type addressGroupBindingNamespaceLister struct {
	listers.ResourceIndexer[*netguardv1beta1.AddressGroupBinding]
}
