/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AddressGroupBindingPolicyLister helps list AddressGroupBindingPolicies.
// All objects returned here must be treated as read-only.
type AddressGroupBindingPolicyLister interface {
	// List lists all AddressGroupBindingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.AddressGroupBindingPolicy, err error)
	// AddressGroupBindingPolicies returns an object that can list and get AddressGroupBindingPolicies.
	AddressGroupBindingPolicies(namespace string) AddressGroupBindingPolicyNamespaceLister
	AddressGroupBindingPolicyListerExpansion
}

// addressGroupBindingPolicyLister implements the AddressGroupBindingPolicyLister interface.
type addressGroupBindingPolicyLister struct {
	listers.ResourceIndexer[*netguardv1beta1.AddressGroupBindingPolicy]
}

// NewAddressGroupBindingPolicyLister returns a new AddressGroupBindingPolicyLister.
func NewAddressGroupBindingPolicyLister(indexer cache.Indexer) AddressGroupBindingPolicyLister {
	return &addressGroupBindingPolicyLister{listers.New[*netguardv1beta1.AddressGroupBindingPolicy](indexer, netguardv1beta1.Resource("addressgroupbindingpolicy"))}
}

// AddressGroupBindingPolicies returns an object that can list and get AddressGroupBindingPolicies.
func (s *addressGroupBindingPolicyLister) AddressGroupBindingPolicies(namespace string) AddressGroupBindingPolicyNamespaceLister {
	return addressGroupBindingPolicyNamespaceLister{listers.NewNamespaced[*netguardv1beta1.AddressGroupBindingPolicy](s.ResourceIndexer, namespace)}
}

// AddressGroupBindingPolicyNamespaceLister helps list and get AddressGroupBindingPolicies.
// All objects returned here must be treated as read-only.
type AddressGroupBindingPolicyNamespaceLister interface {
	// List lists all AddressGroupBindingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.AddressGroupBindingPolicy, err error)
	// Get retrieves the AddressGroupBindingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netguardv1beta1.AddressGroupBindingPolicy, error)
	AddressGroupBindingPolicyNamespaceListerExpansion
}

// addressGroupBindingPolicyNamespaceLister implements the AddressGroupBindingPolicyNamespaceLister
// interface.
type addressGroupBindingPolicyNamespaceLister struct {
	listers.ResourceIndexer[*netguardv1beta1.AddressGroupBindingPolicy]
}
