/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AddressGroupLister helps list AddressGroups.
// All objects returned here must be treated as read-only.
type AddressGroupLister interface {
	// List lists all AddressGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.AddressGroup, err error)
	// AddressGroups returns an object that can list and get AddressGroups.
	AddressGroups(namespace string) AddressGroupNamespaceLister
	AddressGroupListerExpansion
}

// addressGroupLister implements the AddressGroupLister interface.
type addressGroupLister struct {
	listers.ResourceIndexer[*netguardv1beta1.AddressGroup]
}

// NewAddressGroupLister returns a new AddressGroupLister.
func NewAddressGroupLister(indexer cache.Indexer) AddressGroupLister {
	return &addressGroupLister{listers.New[*netguardv1beta1.AddressGroup](indexer, netguardv1beta1.Resource("addressgroup"))}
}

// AddressGroups returns an object that can list and get AddressGroups.
func (s *addressGroupLister) AddressGroups(namespace string) AddressGroupNamespaceLister {
	return addressGroupNamespaceLister{listers.NewNamespaced[*netguardv1beta1.AddressGroup](s.ResourceIndexer, namespace)}
}

// AddressGroupNamespaceLister helps list and get AddressGroups.
// All objects returned here must be treated as read-only.
type AddressGroupNamespaceLister interface {
	// List lists all AddressGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.AddressGroup, err error)
	// Get retrieves the AddressGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netguardv1beta1.AddressGroup, error)
	AddressGroupNamespaceListerExpansion
}

// addressGroupNamespaceLister implements the AddressGroupNamespaceLister
// interface.
type addressGroupNamespaceLister struct {
	listers.ResourceIndexer[*netguardv1beta1.AddressGroup]
}
