/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// AddressGroupListerExpansion allows custom methods to be added to
// AddressGroupLister.
type AddressGroupListerExpansion interface{}

// AddressGroupNamespaceListerExpansion allows custom methods to be added to
// AddressGroupNamespaceLister.
type AddressGroupNamespaceListerExpansion interface{}

// AddressGroupBindingListerExpansion allows custom methods to be added to
// AddressGroupBindingLister.
type AddressGroupBindingListerExpansion interface{}

// AddressGroupBindingNamespaceListerExpansion allows custom methods to be added to
// AddressGroupBindingNamespaceLister.
type AddressGroupBindingNamespaceListerExpansion interface{}

// AddressGroupBindingPolicyListerExpansion allows custom methods to be added to
// AddressGroupBindingPolicyLister.
type AddressGroupBindingPolicyListerExpansion interface{}

// AddressGroupBindingPolicyNamespaceListerExpansion allows custom methods to be added to
// AddressGroupBindingPolicyNamespaceLister.
type AddressGroupBindingPolicyNamespaceListerExpansion interface{}

// AddressGroupPortMappingListerExpansion allows custom methods to be added to
// AddressGroupPortMappingLister.
type AddressGroupPortMappingListerExpansion interface{}

// AddressGroupPortMappingNamespaceListerExpansion allows custom methods to be added to
// AddressGroupPortMappingNamespaceLister.
type AddressGroupPortMappingNamespaceListerExpansion interface{}

// HostListerExpansion allows custom methods to be added to
// HostLister.
type HostListerExpansion interface{}

// HostNamespaceListerExpansion allows custom methods to be added to
// HostNamespaceLister.
type HostNamespaceListerExpansion interface{}

// HostBindingListerExpansion allows custom methods to be added to
// HostBindingLister.
type HostBindingListerExpansion interface{}

// HostBindingNamespaceListerExpansion allows custom methods to be added to
// HostBindingNamespaceLister.
type HostBindingNamespaceListerExpansion interface{}

// NetworkBindingListerExpansion allows custom methods to be added to
// NetworkBindingLister.
type NetworkBindingListerExpansion interface{}

// NetworkBindingNamespaceListerExpansion allows custom methods to be added to
// NetworkBindingNamespaceLister.
type NetworkBindingNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}

// SvcFqdnRuleListerExpansion allows custom methods to be added to
// SvcFqdnRuleLister.
type SvcFqdnRuleListerExpansion interface{}

// SvcFqdnRuleNamespaceListerExpansion allows custom methods to be added to
// SvcFqdnRuleNamespaceLister.
type SvcFqdnRuleNamespaceListerExpansion interface{}

// SvcSvcRuleListerExpansion allows custom methods to be added to
// SvcSvcRuleLister.
type SvcSvcRuleListerExpansion interface{}

// SvcSvcRuleNamespaceListerExpansion allows custom methods to be added to
// SvcSvcRuleNamespaceLister.
type SvcSvcRuleNamespaceListerExpansion interface{}
