/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IEAgAgRuleLister helps list IEAgAgRules.
// All objects returned here must be treated as read-only.
type IEAgAgRuleLister interface {
	// List lists all IEAgAgRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.IEAgAgRule, err error)
	// IEAgAgRules returns an object that can list and get IEAgAgRules.
	IEAgAgRules(namespace string) IEAgAgRuleNamespaceLister
	IEAgAgRuleListerExpansion
}

// iEAgAgRuleLister implements the IEAgAgRuleLister interface.
type iEAgAgRuleLister struct {
	listers.ResourceIndexer[*netguardv1beta1.IEAgAgRule]
}

// NewIEAgAgRuleLister returns a new IEAgAgRuleLister.
func NewIEAgAgRuleLister(indexer cache.Indexer) IEAgAgRuleLister {
	return &iEAgAgRuleLister{listers.New[*netguardv1beta1.IEAgAgRule](indexer, netguardv1beta1.Resource("ieagagrule"))}
}

// IEAgAgRules returns an object that can list and get IEAgAgRules.
func (s *iEAgAgRuleLister) IEAgAgRules(namespace string) IEAgAgRuleNamespaceLister {
	return iEAgAgRuleNamespaceLister{listers.NewNamespaced[*netguardv1beta1.IEAgAgRule](s.ResourceIndexer, namespace)}
}

// IEAgAgRuleNamespaceLister helps list and get IEAgAgRules.
// All objects returned here must be treated as read-only.
type IEAgAgRuleNamespaceLister interface {
	// List lists all IEAgAgRules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.IEAgAgRule, err error)
	// Get retrieves the IEAgAgRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netguardv1beta1.IEAgAgRule, error)
	IEAgAgRuleNamespaceListerExpansion
}

// iEAgAgRuleNamespaceLister implements the IEAgAgRuleNamespaceLister
// interface.
type iEAgAgRuleNamespaceLister struct {
	listers.ResourceIndexer[*netguardv1beta1.IEAgAgRule]
}
