/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkBindingLister helps list NetworkBindings.
// All objects returned here must be treated as read-only.
type NetworkBindingLister interface {
	// List lists all NetworkBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.NetworkBinding, err error)
	// NetworkBindings returns an object that can list and get NetworkBindings.
	NetworkBindings(namespace string) NetworkBindingNamespaceLister
	NetworkBindingListerExpansion
}

// networkBindingLister implements the NetworkBindingLister interface.
type networkBindingLister struct {
	listers.ResourceIndexer[*netguardv1beta1.NetworkBinding]
}

// NewNetworkBindingLister returns a new NetworkBindingLister.
func NewNetworkBindingLister(indexer cache.Indexer) NetworkBindingLister {
	return &networkBindingLister{listers.New[*netguardv1beta1.NetworkBinding](indexer, netguardv1beta1.Resource("networkbinding"))}
}

// NetworkBindings returns an object that can list and get NetworkBindings.
func (s *networkBindingLister) NetworkBindings(namespace string) NetworkBindingNamespaceLister {
	return networkBindingNamespaceLister{listers.NewNamespaced[*netguardv1beta1.NetworkBinding](s.ResourceIndexer, namespace)}
}

// NetworkBindingNamespaceLister helps list and get NetworkBindings.
// All objects returned here must be treated as read-only.
type NetworkBindingNamespaceLister interface {
	// List lists all NetworkBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.NetworkBinding, err error)
	// Get retrieves the NetworkBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netguardv1beta1.NetworkBinding, error)
	NetworkBindingNamespaceListerExpansion
}

// networkBindingNamespaceLister implements the NetworkBindingNamespaceLister
// interface.
type networkBindingNamespaceLister struct {
	listers.ResourceIndexer[*netguardv1beta1.NetworkBinding]
}
