/*
Copyright 2024 The PRO-Robotech Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceAliasLister helps list ServiceAliases.
// All objects returned here must be treated as read-only.
type ServiceAliasLister interface {
	// List lists all ServiceAliases in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.ServiceAlias, err error)
	// ServiceAliases returns an object that can list and get ServiceAliases.
	ServiceAliases(namespace string) ServiceAliasNamespaceLister
	ServiceAliasListerExpansion
}

// serviceAliasLister implements the ServiceAliasLister interface.
type serviceAliasLister struct {
	listers.ResourceIndexer[*netguardv1beta1.ServiceAlias]
}

// NewServiceAliasLister returns a new ServiceAliasLister.
func NewServiceAliasLister(indexer cache.Indexer) ServiceAliasLister {
	return &serviceAliasLister{listers.New[*netguardv1beta1.ServiceAlias](indexer, netguardv1beta1.Resource("servicealias"))}
}

// ServiceAliases returns an object that can list and get ServiceAliases.
func (s *serviceAliasLister) ServiceAliases(namespace string) ServiceAliasNamespaceLister {
	return serviceAliasNamespaceLister{listers.NewNamespaced[*netguardv1beta1.ServiceAlias](s.ResourceIndexer, namespace)}
}

// ServiceAliasNamespaceLister helps list and get ServiceAliases.
// All objects returned here must be treated as read-only.
type ServiceAliasNamespaceLister interface {
	// List lists all ServiceAliases in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.ServiceAlias, err error)
	// Get retrieves the ServiceAlias from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netguardv1beta1.ServiceAlias, error)
	ServiceAliasNamespaceListerExpansion
}

// serviceAliasNamespaceLister implements the ServiceAliasNamespaceLister
// interface.
type serviceAliasNamespaceLister struct {
	listers.ResourceIndexer[*netguardv1beta1.ServiceAlias]
}
