/*
Copyright 2024 The Netguard Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SvcFqdnRuleLister helps list SvcFqdnRules.
// All objects returned here must be treated as read-only.
type SvcFqdnRuleLister interface {
	// List lists all SvcFqdnRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.SvcFqdnRule, err error)
	// SvcFqdnRules returns an object that can list and get SvcFqdnRules.
	SvcFqdnRules(namespace string) SvcFqdnRuleNamespaceLister
	SvcFqdnRuleListerExpansion
}

// svcFqdnRuleLister implements the SvcFqdnRuleLister interface.
type svcFqdnRuleLister struct {
	listers.ResourceIndexer[*netguardv1beta1.SvcFqdnRule]
}

// NewSvcFqdnRuleLister returns a new SvcFqdnRuleLister.
func NewSvcFqdnRuleLister(indexer cache.Indexer) SvcFqdnRuleLister {
	return &svcFqdnRuleLister{listers.New[*netguardv1beta1.SvcFqdnRule](indexer, netguardv1beta1.Resource("svcfqdnrule"))}
}

// SvcFqdnRules returns an object that can list and get SvcFqdnRules.
func (s *svcFqdnRuleLister) SvcFqdnRules(namespace string) SvcFqdnRuleNamespaceLister {
	return svcFqdnRuleNamespaceLister{listers.NewNamespaced[*netguardv1beta1.SvcFqdnRule](s.ResourceIndexer, namespace)}
}

// SvcFqdnRuleNamespaceLister helps list and get SvcFqdnRules.
// All objects returned here must be treated as read-only.
type SvcFqdnRuleNamespaceLister interface {
	// List lists all SvcFqdnRules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*netguardv1beta1.SvcFqdnRule, err error)
	// Get retrieves the SvcFqdnRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*netguardv1beta1.SvcFqdnRule, error)
	SvcFqdnRuleNamespaceListerExpansion
}

// svcFqdnRuleNamespaceLister implements the SvcFqdnRuleNamespaceLister
// interface.
type svcFqdnRuleNamespaceLister struct {
	listers.ResourceIndexer[*netguardv1beta1.SvcFqdnRule]
}
