apiVersion: apps/v1
kind: Deployment
metadata:
  name: netguard-backend
  namespace: netguard-system
  labels:
    app: netguard-backend
    variant: memory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netguard-backend
  template:
    metadata:
      labels:
        app: netguard-backend
        variant: memory
    spec:
      containers:
      - name: backend
        image: netguard/pg-backend:latest
        imagePullPolicy: IfNotPresent
        command: ["/root/server"]
        args:
        - --memory                    # 🧠 In-memory database mode
        - --grpc-addr=:9090
        - --http-addr=:8080
        ports:
        - containerPort: 9090
          name: grpc
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"           # Lower resource requirements for memory mode
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nc -z localhost 9090"
          initialDelaySeconds: 10     # Faster startup with in-memory
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nc -z localhost 9090"
          initialDelaySeconds: 5      # Quick readiness with in-memory
          periodSeconds: 5
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: BACKEND_MODE
          value: "memory"
---
apiVersion: v1
kind: Service
metadata:
  name: netguard-backend
  namespace: netguard-system
  labels:
    app: netguard-backend
    variant: memory
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: netguard-backend