//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package ieagagrule

import (
	"netguard-pg-backend/internal/domain/models"
	netguardv1beta1 "netguard-pg-backend/internal/k8s/apis/netguard/v1beta1"
	"netguard-pg-backend/internal/k8s/registry/base"
)

// NewStatusREST creates a status subresource for IEAgAgRule that supports condition updates.
// This allows the backend condition processing to persist status.conditions to Kubernetes objects.
func NewStatusREST(store *IEAgAgRuleStorage) *base.StatusREST[*netguardv1beta1.IEAgAgRule, *models.IEAgAgRule] {
	return base.NewStatusREST[*netguardv1beta1.IEAgAgRule, *models.IEAgAgRule](
		store.BaseStorage,
	)
}
