syntax = "proto3";

package netguard.v1;

option go_package = "netguard-pg-backend/protos/pkg/api/netguard;netguard";

import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "netguard/api.proto";
import "netguard/watch.proto";

service NetguardService {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_tag) = {
    description: "Netguard API service"
  };

  rpc Sync(SyncReq) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/v1/sync"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "Sync: makes changes in DB";
    };
  }

  rpc SyncStatus(google.protobuf.Empty) returns(SyncStatusResp) {
    option (google.api.http) = {
      get: "/v1/sync/status"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "SyncStatus: gets last succeeded update DB status";
    };
  }

  rpc MarkForDeletion(MarkForDeletionReq) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/v1/{kind}/{namespace}/{name}:markForDeletion"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "MarkForDeletion: marks resource for soft deletion";
    };
  }

  rpc ListServices(ListServicesReq) returns (ListServicesResp) {
    option (google.api.http) = {
      get: "/v1/services"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListServices: gets list of services";
    };
  }

  rpc GetService(GetServiceReq) returns (GetServiceResp) {
    option (google.api.http) = {
      get: "/v1/services/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetService: gets a specific service by ID";
    };
  }

  rpc ListAddressGroups(ListAddressGroupsReq) returns (ListAddressGroupsResp) {
    option (google.api.http) = {
      get: "/v1/address-groups"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListAddressGroups: gets list of address groups";
    };
  }

  rpc GetAddressGroup(GetAddressGroupReq) returns (GetAddressGroupResp) {
    option (google.api.http) = {
      get: "/v1/address-groups/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetAddressGroup: gets a specific address group by ID";
    };
  }

  rpc ListAddressGroupBindings(ListAddressGroupBindingsReq) returns (ListAddressGroupBindingsResp) {
    option (google.api.http) = {
      get: "/v1/address-group-bindings"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListAddressGroupBindings: gets list of address group bindings";
    };
  }

  rpc GetAddressGroupBinding(GetAddressGroupBindingReq) returns (GetAddressGroupBindingResp) {
    option (google.api.http) = {
      get: "/v1/address-group-bindings/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetAddressGroupBinding: gets a specific address group binding by ID";
    };
  }

  rpc ListAddressGroupPortMappings(ListAddressGroupPortMappingsReq) returns (ListAddressGroupPortMappingsResp) {
    option (google.api.http) = {
      get: "/v1/address-group-port-mappings"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListAddressGroupPortMappings: gets list of address group port mappings";
    };
  }

  rpc GetAddressGroupPortMapping(GetAddressGroupPortMappingReq) returns (GetAddressGroupPortMappingResp) {
    option (google.api.http) = {
      get: "/v1/address-group-port-mappings/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetAddressGroupPortMapping: gets a specific address group port mapping by ID";
    };
  }

  rpc ListAddressGroupBindingPolicies(ListAddressGroupBindingPoliciesReq) returns (ListAddressGroupBindingPoliciesResp) {
    option (google.api.http) = {
      get: "/v1/address-group-binding-policies"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListAddressGroupBindingPolicies: gets list of address group binding policies";
    };
  }

  rpc GetAddressGroupBindingPolicy(GetAddressGroupBindingPolicyReq) returns (GetAddressGroupBindingPolicyResp) {
    option (google.api.http) = {
      get: "/v1/address-group-binding-policies/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetAddressGroupBindingPolicy: gets a specific address group binding policy by ID";
    };
  }

  rpc ListHosts(ListHostsReq) returns (ListHostsResp) {
    option (google.api.http) = {
      get: "/v1/hosts"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListHosts: gets list of hosts";
    };
  }

  rpc GetHost(GetHostReq) returns (GetHostResp) {
    option (google.api.http) = {
      get: "/v1/hosts/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetHost: gets a specific host by ID";
    };
  }

  rpc ListHostBindings(ListHostBindingsReq) returns (ListHostBindingsResp) {
    option (google.api.http) = {
      get: "/v1/host-bindings"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListHostBindings: gets list of host bindings";
    };
  }

  rpc GetHostBinding(GetHostBindingReq) returns (GetHostBindingResp) {
    option (google.api.http) = {
      get: "/v1/host-bindings/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetHostBinding: gets a specific host binding by ID";
    };
  }

  rpc ListNetworks(ListNetworksReq) returns (ListNetworksResp) {
    option (google.api.http) = {
      get: "/v1/networks"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListNetworks: gets list of networks";
    };
  }

  rpc GetNetwork(GetNetworkReq) returns (GetNetworkResp) {
    option (google.api.http) = {
      get: "/v1/networks/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetNetwork: gets a specific network by ID";
    };
  }

  rpc ListNetworkBindings(ListNetworkBindingsReq) returns (ListNetworkBindingsResp) {
    option (google.api.http) = {
      get: "/v1/network-bindings"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListNetworkBindings: gets list of network bindings";
    };
  }

  rpc GetNetworkBinding(GetNetworkBindingReq) returns (GetNetworkBindingResp) {
    option (google.api.http) = {
      get: "/v1/network-bindings/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetNetworkBinding: gets a specific network binding by ID";
    };
  }

  rpc ListSvcSvcRules(ListSvcSvcRulesReq) returns (ListSvcSvcRulesResp) {
    option (google.api.http) = {
      get: "/v1/svc-svc-rules"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListSvcSvcRules: gets list of SvcSvc rules";
    };
  }

  rpc GetSvcSvcRule(GetSvcSvcRuleReq) returns (GetSvcSvcRuleResp) {
    option (google.api.http) = {
      get: "/v1/svc-svc-rules/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetSvcSvcRule: gets a specific SvcSvc rule by ID";
    };
  }

  rpc ListSvcFqdnRules(ListSvcFqdnRulesReq) returns (ListSvcFqdnRulesResp) {
    option (google.api.http) = {
      get: "/v1/svc-fqdn-rules"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "ListSvcFqdnRules: gets list of SvcFqdn rules";
    };
  }

  rpc GetSvcFqdnRule(GetSvcFqdnRuleReq) returns (GetSvcFqdnRuleResp) {
    option (google.api.http) = {
      get: "/v1/svc-fqdn-rules/{identifier.namespace}/{identifier.name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      description: "GetSvcFqdnRule: gets a specific SvcFqdn rule by ID";
    };
  }

  rpc WatchServices(WatchRequest) returns (stream WatchEvent);
  rpc WatchAddressGroups(WatchRequest) returns (stream WatchEvent);
  rpc WatchAddressGroupBindings(WatchRequest) returns (stream WatchEvent);
  rpc WatchAddressGroupPortMappings(WatchRequest) returns (stream WatchEvent);
  rpc WatchAddressGroupBindingPolicies(WatchRequest) returns (stream WatchEvent);
  rpc WatchHosts(WatchRequest) returns (stream WatchEvent);
  rpc WatchHostBindings(WatchRequest) returns (stream WatchEvent);
  rpc WatchNetworks(WatchRequest) returns (stream WatchEvent);
  rpc WatchNetworkBindings(WatchRequest) returns (stream WatchEvent);
  rpc WatchSvcSvcRules(WatchRequest) returns (stream WatchEvent);
  rpc WatchSvcFqdnRules(WatchRequest) returns (stream WatchEvent);
}

