# gRPC настройки
endpoint: "localhost:8080"
max_retries: 3
connect_timeout: "10s"
request_timeout: "30s"

# Rate Limiting (100 запросов/сек с burst 200)
rate_limit: 100.0
rate_burst: 200

# Circuit Breaker
cb_max_requests: 5        # Максимум запросов в half-open состоянии
cb_interval: "60s"        # Интервал сброса счетчиков
cb_timeout: "60s"         # Таймаут в open состоянии
cb_failure_threshold: 5   # Количество ошибок для открытия

# Cache
cache_default_ttl: "5m"
cache_cleanup_interval: "10m" 