# config/samples/flow/missing-bindings-v1beta1.yaml
# Недостающие AddressGroupBindingPolicy для связи сервисов с адресными группами
# Эти binding'и необходимы для автоматического создания IEAGAG правил из RuleS2S
# Используется правильная версия API netguard.sgroups.io/v1beta1 для netguard-backend проекта
---
# Binding'и для namespace application
# web service bindings
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: web-ingress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: web
    namespace: application
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: ingress-application
    namespace: application
---
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: web-egress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: web
    namespace: application
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: egress-application
    namespace: application
---
# backend service bindings
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: backend-ingress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: backend
    namespace: application
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: ingress-application
    namespace: application
---
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: backend-egress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: backend
    namespace: application
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: egress-application
    namespace: application
---
# Cross-namespace bindings для backend с infra адресными группами
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: backend-ingress-infra
  namespace: infra
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: backend
    namespace: application
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: ingress-infra
    namespace: infra
---
# backend-egress-infra уже существует в example-flow.yaml
# Binding'и для namespace infra
# postgress service bindings
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: postgress-ingress-infra
  namespace: infra
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: postgress
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: ingress-infra
    namespace: infra
---
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: postgress-egress-infra
  namespace: infra
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: postgress
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: egress-infra
    namespace: infra
---
# Cross-namespace bindings для postgress с application адресными группами
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: postgress-ingress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: postgress
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: ingress-application
    namespace: application
---
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: postgress-egress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: postgress
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: egress-application
    namespace: application
---
# logs service bindings
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: logs-ingress-infra
  namespace: infra
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: logs
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: ingress-infra
    namespace: infra
---
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: logs-egress-infra
  namespace: infra
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: logs
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: egress-infra
    namespace: infra
---
# Cross-namespace bindings для logs с application адресными группами
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: logs-ingress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: logs
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: ingress-application
    namespace: application
---
apiVersion: netguard.sgroups.io/v1beta1
kind: AddressGroupBindingPolicy
metadata:
  name: logs-egress-application
  namespace: application
spec:
  serviceRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: Service
    name: logs
    namespace: infra
  addressGroupRef:
    apiVersion: netguard.sgroups.io/v1beta1
    kind: AddressGroup
    name: egress-application
    namespace: application