// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: netguard/service.proto

package netguardconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	netguard "netguard-pg-backend/protos/pkg/api/netguard"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NetguardServiceName is the fully-qualified name of the NetguardService service.
	NetguardServiceName = "netguard.v1.NetguardService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NetguardServiceSyncProcedure is the fully-qualified name of the NetguardService's Sync RPC.
	NetguardServiceSyncProcedure = "/netguard.v1.NetguardService/Sync"
	// NetguardServiceSyncStatusProcedure is the fully-qualified name of the NetguardService's
	// SyncStatus RPC.
	NetguardServiceSyncStatusProcedure = "/netguard.v1.NetguardService/SyncStatus"
	// NetguardServiceMarkForDeletionProcedure is the fully-qualified name of the NetguardService's
	// MarkForDeletion RPC.
	NetguardServiceMarkForDeletionProcedure = "/netguard.v1.NetguardService/MarkForDeletion"
	// NetguardServiceListServicesProcedure is the fully-qualified name of the NetguardService's
	// ListServices RPC.
	NetguardServiceListServicesProcedure = "/netguard.v1.NetguardService/ListServices"
	// NetguardServiceGetServiceProcedure is the fully-qualified name of the NetguardService's
	// GetService RPC.
	NetguardServiceGetServiceProcedure = "/netguard.v1.NetguardService/GetService"
	// NetguardServiceListAddressGroupsProcedure is the fully-qualified name of the NetguardService's
	// ListAddressGroups RPC.
	NetguardServiceListAddressGroupsProcedure = "/netguard.v1.NetguardService/ListAddressGroups"
	// NetguardServiceGetAddressGroupProcedure is the fully-qualified name of the NetguardService's
	// GetAddressGroup RPC.
	NetguardServiceGetAddressGroupProcedure = "/netguard.v1.NetguardService/GetAddressGroup"
	// NetguardServiceListAddressGroupBindingsProcedure is the fully-qualified name of the
	// NetguardService's ListAddressGroupBindings RPC.
	NetguardServiceListAddressGroupBindingsProcedure = "/netguard.v1.NetguardService/ListAddressGroupBindings"
	// NetguardServiceGetAddressGroupBindingProcedure is the fully-qualified name of the
	// NetguardService's GetAddressGroupBinding RPC.
	NetguardServiceGetAddressGroupBindingProcedure = "/netguard.v1.NetguardService/GetAddressGroupBinding"
	// NetguardServiceListAddressGroupPortMappingsProcedure is the fully-qualified name of the
	// NetguardService's ListAddressGroupPortMappings RPC.
	NetguardServiceListAddressGroupPortMappingsProcedure = "/netguard.v1.NetguardService/ListAddressGroupPortMappings"
	// NetguardServiceGetAddressGroupPortMappingProcedure is the fully-qualified name of the
	// NetguardService's GetAddressGroupPortMapping RPC.
	NetguardServiceGetAddressGroupPortMappingProcedure = "/netguard.v1.NetguardService/GetAddressGroupPortMapping"
	// NetguardServiceListAddressGroupBindingPoliciesProcedure is the fully-qualified name of the
	// NetguardService's ListAddressGroupBindingPolicies RPC.
	NetguardServiceListAddressGroupBindingPoliciesProcedure = "/netguard.v1.NetguardService/ListAddressGroupBindingPolicies"
	// NetguardServiceGetAddressGroupBindingPolicyProcedure is the fully-qualified name of the
	// NetguardService's GetAddressGroupBindingPolicy RPC.
	NetguardServiceGetAddressGroupBindingPolicyProcedure = "/netguard.v1.NetguardService/GetAddressGroupBindingPolicy"
	// NetguardServiceListHostsProcedure is the fully-qualified name of the NetguardService's ListHosts
	// RPC.
	NetguardServiceListHostsProcedure = "/netguard.v1.NetguardService/ListHosts"
	// NetguardServiceGetHostProcedure is the fully-qualified name of the NetguardService's GetHost RPC.
	NetguardServiceGetHostProcedure = "/netguard.v1.NetguardService/GetHost"
	// NetguardServiceListHostBindingsProcedure is the fully-qualified name of the NetguardService's
	// ListHostBindings RPC.
	NetguardServiceListHostBindingsProcedure = "/netguard.v1.NetguardService/ListHostBindings"
	// NetguardServiceGetHostBindingProcedure is the fully-qualified name of the NetguardService's
	// GetHostBinding RPC.
	NetguardServiceGetHostBindingProcedure = "/netguard.v1.NetguardService/GetHostBinding"
	// NetguardServiceListNetworksProcedure is the fully-qualified name of the NetguardService's
	// ListNetworks RPC.
	NetguardServiceListNetworksProcedure = "/netguard.v1.NetguardService/ListNetworks"
	// NetguardServiceGetNetworkProcedure is the fully-qualified name of the NetguardService's
	// GetNetwork RPC.
	NetguardServiceGetNetworkProcedure = "/netguard.v1.NetguardService/GetNetwork"
	// NetguardServiceListNetworkBindingsProcedure is the fully-qualified name of the NetguardService's
	// ListNetworkBindings RPC.
	NetguardServiceListNetworkBindingsProcedure = "/netguard.v1.NetguardService/ListNetworkBindings"
	// NetguardServiceGetNetworkBindingProcedure is the fully-qualified name of the NetguardService's
	// GetNetworkBinding RPC.
	NetguardServiceGetNetworkBindingProcedure = "/netguard.v1.NetguardService/GetNetworkBinding"
	// NetguardServiceListSvcSvcRulesProcedure is the fully-qualified name of the NetguardService's
	// ListSvcSvcRules RPC.
	NetguardServiceListSvcSvcRulesProcedure = "/netguard.v1.NetguardService/ListSvcSvcRules"
	// NetguardServiceGetSvcSvcRuleProcedure is the fully-qualified name of the NetguardService's
	// GetSvcSvcRule RPC.
	NetguardServiceGetSvcSvcRuleProcedure = "/netguard.v1.NetguardService/GetSvcSvcRule"
	// NetguardServiceListSvcFqdnRulesProcedure is the fully-qualified name of the NetguardService's
	// ListSvcFqdnRules RPC.
	NetguardServiceListSvcFqdnRulesProcedure = "/netguard.v1.NetguardService/ListSvcFqdnRules"
	// NetguardServiceGetSvcFqdnRuleProcedure is the fully-qualified name of the NetguardService's
	// GetSvcFqdnRule RPC.
	NetguardServiceGetSvcFqdnRuleProcedure = "/netguard.v1.NetguardService/GetSvcFqdnRule"
	// NetguardServiceListIECidrSvcRulesProcedure is the fully-qualified name of the NetguardService's
	// ListIECidrSvcRules RPC.
	NetguardServiceListIECidrSvcRulesProcedure = "/netguard.v1.NetguardService/ListIECidrSvcRules"
	// NetguardServiceGetIECidrSvcRuleProcedure is the fully-qualified name of the NetguardService's
	// GetIECidrSvcRule RPC.
	NetguardServiceGetIECidrSvcRuleProcedure = "/netguard.v1.NetguardService/GetIECidrSvcRule"
	// NetguardServiceWatchServicesProcedure is the fully-qualified name of the NetguardService's
	// WatchServices RPC.
	NetguardServiceWatchServicesProcedure = "/netguard.v1.NetguardService/WatchServices"
	// NetguardServiceWatchAddressGroupsProcedure is the fully-qualified name of the NetguardService's
	// WatchAddressGroups RPC.
	NetguardServiceWatchAddressGroupsProcedure = "/netguard.v1.NetguardService/WatchAddressGroups"
	// NetguardServiceWatchAddressGroupBindingsProcedure is the fully-qualified name of the
	// NetguardService's WatchAddressGroupBindings RPC.
	NetguardServiceWatchAddressGroupBindingsProcedure = "/netguard.v1.NetguardService/WatchAddressGroupBindings"
	// NetguardServiceWatchAddressGroupPortMappingsProcedure is the fully-qualified name of the
	// NetguardService's WatchAddressGroupPortMappings RPC.
	NetguardServiceWatchAddressGroupPortMappingsProcedure = "/netguard.v1.NetguardService/WatchAddressGroupPortMappings"
	// NetguardServiceWatchAddressGroupBindingPoliciesProcedure is the fully-qualified name of the
	// NetguardService's WatchAddressGroupBindingPolicies RPC.
	NetguardServiceWatchAddressGroupBindingPoliciesProcedure = "/netguard.v1.NetguardService/WatchAddressGroupBindingPolicies"
	// NetguardServiceWatchHostsProcedure is the fully-qualified name of the NetguardService's
	// WatchHosts RPC.
	NetguardServiceWatchHostsProcedure = "/netguard.v1.NetguardService/WatchHosts"
	// NetguardServiceWatchHostBindingsProcedure is the fully-qualified name of the NetguardService's
	// WatchHostBindings RPC.
	NetguardServiceWatchHostBindingsProcedure = "/netguard.v1.NetguardService/WatchHostBindings"
	// NetguardServiceWatchNetworksProcedure is the fully-qualified name of the NetguardService's
	// WatchNetworks RPC.
	NetguardServiceWatchNetworksProcedure = "/netguard.v1.NetguardService/WatchNetworks"
	// NetguardServiceWatchNetworkBindingsProcedure is the fully-qualified name of the NetguardService's
	// WatchNetworkBindings RPC.
	NetguardServiceWatchNetworkBindingsProcedure = "/netguard.v1.NetguardService/WatchNetworkBindings"
	// NetguardServiceWatchSvcSvcRulesProcedure is the fully-qualified name of the NetguardService's
	// WatchSvcSvcRules RPC.
	NetguardServiceWatchSvcSvcRulesProcedure = "/netguard.v1.NetguardService/WatchSvcSvcRules"
	// NetguardServiceWatchSvcFqdnRulesProcedure is the fully-qualified name of the NetguardService's
	// WatchSvcFqdnRules RPC.
	NetguardServiceWatchSvcFqdnRulesProcedure = "/netguard.v1.NetguardService/WatchSvcFqdnRules"
	// NetguardServiceWatchIECidrSvcRulesProcedure is the fully-qualified name of the NetguardService's
	// WatchIECidrSvcRules RPC.
	NetguardServiceWatchIECidrSvcRulesProcedure = "/netguard.v1.NetguardService/WatchIECidrSvcRules"
)

// NetguardServiceClient is a client for the netguard.v1.NetguardService service.
type NetguardServiceClient interface {
	Sync(context.Context, *connect.Request[netguard.SyncReq]) (*connect.Response[emptypb.Empty], error)
	SyncStatus(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[netguard.SyncStatusResp], error)
	MarkForDeletion(context.Context, *connect.Request[netguard.MarkForDeletionReq]) (*connect.Response[emptypb.Empty], error)
	ListServices(context.Context, *connect.Request[netguard.ListServicesReq]) (*connect.Response[netguard.ListServicesResp], error)
	GetService(context.Context, *connect.Request[netguard.GetServiceReq]) (*connect.Response[netguard.GetServiceResp], error)
	ListAddressGroups(context.Context, *connect.Request[netguard.ListAddressGroupsReq]) (*connect.Response[netguard.ListAddressGroupsResp], error)
	GetAddressGroup(context.Context, *connect.Request[netguard.GetAddressGroupReq]) (*connect.Response[netguard.GetAddressGroupResp], error)
	ListAddressGroupBindings(context.Context, *connect.Request[netguard.ListAddressGroupBindingsReq]) (*connect.Response[netguard.ListAddressGroupBindingsResp], error)
	GetAddressGroupBinding(context.Context, *connect.Request[netguard.GetAddressGroupBindingReq]) (*connect.Response[netguard.GetAddressGroupBindingResp], error)
	ListAddressGroupPortMappings(context.Context, *connect.Request[netguard.ListAddressGroupPortMappingsReq]) (*connect.Response[netguard.ListAddressGroupPortMappingsResp], error)
	GetAddressGroupPortMapping(context.Context, *connect.Request[netguard.GetAddressGroupPortMappingReq]) (*connect.Response[netguard.GetAddressGroupPortMappingResp], error)
	ListAddressGroupBindingPolicies(context.Context, *connect.Request[netguard.ListAddressGroupBindingPoliciesReq]) (*connect.Response[netguard.ListAddressGroupBindingPoliciesResp], error)
	GetAddressGroupBindingPolicy(context.Context, *connect.Request[netguard.GetAddressGroupBindingPolicyReq]) (*connect.Response[netguard.GetAddressGroupBindingPolicyResp], error)
	ListHosts(context.Context, *connect.Request[netguard.ListHostsReq]) (*connect.Response[netguard.ListHostsResp], error)
	GetHost(context.Context, *connect.Request[netguard.GetHostReq]) (*connect.Response[netguard.GetHostResp], error)
	ListHostBindings(context.Context, *connect.Request[netguard.ListHostBindingsReq]) (*connect.Response[netguard.ListHostBindingsResp], error)
	GetHostBinding(context.Context, *connect.Request[netguard.GetHostBindingReq]) (*connect.Response[netguard.GetHostBindingResp], error)
	ListNetworks(context.Context, *connect.Request[netguard.ListNetworksReq]) (*connect.Response[netguard.ListNetworksResp], error)
	GetNetwork(context.Context, *connect.Request[netguard.GetNetworkReq]) (*connect.Response[netguard.GetNetworkResp], error)
	ListNetworkBindings(context.Context, *connect.Request[netguard.ListNetworkBindingsReq]) (*connect.Response[netguard.ListNetworkBindingsResp], error)
	GetNetworkBinding(context.Context, *connect.Request[netguard.GetNetworkBindingReq]) (*connect.Response[netguard.GetNetworkBindingResp], error)
	ListSvcSvcRules(context.Context, *connect.Request[netguard.ListSvcSvcRulesReq]) (*connect.Response[netguard.ListSvcSvcRulesResp], error)
	GetSvcSvcRule(context.Context, *connect.Request[netguard.GetSvcSvcRuleReq]) (*connect.Response[netguard.GetSvcSvcRuleResp], error)
	ListSvcFqdnRules(context.Context, *connect.Request[netguard.ListSvcFqdnRulesReq]) (*connect.Response[netguard.ListSvcFqdnRulesResp], error)
	GetSvcFqdnRule(context.Context, *connect.Request[netguard.GetSvcFqdnRuleReq]) (*connect.Response[netguard.GetSvcFqdnRuleResp], error)
	ListIECidrSvcRules(context.Context, *connect.Request[netguard.ListIECidrSvcRulesReq]) (*connect.Response[netguard.ListIECidrSvcRulesResp], error)
	GetIECidrSvcRule(context.Context, *connect.Request[netguard.GetIECidrSvcRuleReq]) (*connect.Response[netguard.GetIECidrSvcRuleResp], error)
	WatchServices(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchAddressGroups(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchAddressGroupBindings(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchAddressGroupPortMappings(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchAddressGroupBindingPolicies(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchHosts(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchHostBindings(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchNetworks(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchNetworkBindings(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchSvcSvcRules(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchSvcFqdnRules(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
	WatchIECidrSvcRules(context.Context, *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error)
}

// NewNetguardServiceClient constructs a client for the netguard.v1.NetguardService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNetguardServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NetguardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	netguardServiceMethods := netguard.File_netguard_service_proto.Services().ByName("NetguardService").Methods()
	return &netguardServiceClient{
		sync: connect.NewClient[netguard.SyncReq, emptypb.Empty](
			httpClient,
			baseURL+NetguardServiceSyncProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
		syncStatus: connect.NewClient[emptypb.Empty, netguard.SyncStatusResp](
			httpClient,
			baseURL+NetguardServiceSyncStatusProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("SyncStatus")),
			connect.WithClientOptions(opts...),
		),
		markForDeletion: connect.NewClient[netguard.MarkForDeletionReq, emptypb.Empty](
			httpClient,
			baseURL+NetguardServiceMarkForDeletionProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("MarkForDeletion")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[netguard.ListServicesReq, netguard.ListServicesResp](
			httpClient,
			baseURL+NetguardServiceListServicesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		getService: connect.NewClient[netguard.GetServiceReq, netguard.GetServiceResp](
			httpClient,
			baseURL+NetguardServiceGetServiceProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetService")),
			connect.WithClientOptions(opts...),
		),
		listAddressGroups: connect.NewClient[netguard.ListAddressGroupsReq, netguard.ListAddressGroupsResp](
			httpClient,
			baseURL+NetguardServiceListAddressGroupsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroups")),
			connect.WithClientOptions(opts...),
		),
		getAddressGroup: connect.NewClient[netguard.GetAddressGroupReq, netguard.GetAddressGroupResp](
			httpClient,
			baseURL+NetguardServiceGetAddressGroupProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroup")),
			connect.WithClientOptions(opts...),
		),
		listAddressGroupBindings: connect.NewClient[netguard.ListAddressGroupBindingsReq, netguard.ListAddressGroupBindingsResp](
			httpClient,
			baseURL+NetguardServiceListAddressGroupBindingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroupBindings")),
			connect.WithClientOptions(opts...),
		),
		getAddressGroupBinding: connect.NewClient[netguard.GetAddressGroupBindingReq, netguard.GetAddressGroupBindingResp](
			httpClient,
			baseURL+NetguardServiceGetAddressGroupBindingProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroupBinding")),
			connect.WithClientOptions(opts...),
		),
		listAddressGroupPortMappings: connect.NewClient[netguard.ListAddressGroupPortMappingsReq, netguard.ListAddressGroupPortMappingsResp](
			httpClient,
			baseURL+NetguardServiceListAddressGroupPortMappingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroupPortMappings")),
			connect.WithClientOptions(opts...),
		),
		getAddressGroupPortMapping: connect.NewClient[netguard.GetAddressGroupPortMappingReq, netguard.GetAddressGroupPortMappingResp](
			httpClient,
			baseURL+NetguardServiceGetAddressGroupPortMappingProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroupPortMapping")),
			connect.WithClientOptions(opts...),
		),
		listAddressGroupBindingPolicies: connect.NewClient[netguard.ListAddressGroupBindingPoliciesReq, netguard.ListAddressGroupBindingPoliciesResp](
			httpClient,
			baseURL+NetguardServiceListAddressGroupBindingPoliciesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroupBindingPolicies")),
			connect.WithClientOptions(opts...),
		),
		getAddressGroupBindingPolicy: connect.NewClient[netguard.GetAddressGroupBindingPolicyReq, netguard.GetAddressGroupBindingPolicyResp](
			httpClient,
			baseURL+NetguardServiceGetAddressGroupBindingPolicyProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroupBindingPolicy")),
			connect.WithClientOptions(opts...),
		),
		listHosts: connect.NewClient[netguard.ListHostsReq, netguard.ListHostsResp](
			httpClient,
			baseURL+NetguardServiceListHostsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListHosts")),
			connect.WithClientOptions(opts...),
		),
		getHost: connect.NewClient[netguard.GetHostReq, netguard.GetHostResp](
			httpClient,
			baseURL+NetguardServiceGetHostProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetHost")),
			connect.WithClientOptions(opts...),
		),
		listHostBindings: connect.NewClient[netguard.ListHostBindingsReq, netguard.ListHostBindingsResp](
			httpClient,
			baseURL+NetguardServiceListHostBindingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListHostBindings")),
			connect.WithClientOptions(opts...),
		),
		getHostBinding: connect.NewClient[netguard.GetHostBindingReq, netguard.GetHostBindingResp](
			httpClient,
			baseURL+NetguardServiceGetHostBindingProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetHostBinding")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[netguard.ListNetworksReq, netguard.ListNetworksResp](
			httpClient,
			baseURL+NetguardServiceListNetworksProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		getNetwork: connect.NewClient[netguard.GetNetworkReq, netguard.GetNetworkResp](
			httpClient,
			baseURL+NetguardServiceGetNetworkProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetNetwork")),
			connect.WithClientOptions(opts...),
		),
		listNetworkBindings: connect.NewClient[netguard.ListNetworkBindingsReq, netguard.ListNetworkBindingsResp](
			httpClient,
			baseURL+NetguardServiceListNetworkBindingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListNetworkBindings")),
			connect.WithClientOptions(opts...),
		),
		getNetworkBinding: connect.NewClient[netguard.GetNetworkBindingReq, netguard.GetNetworkBindingResp](
			httpClient,
			baseURL+NetguardServiceGetNetworkBindingProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetNetworkBinding")),
			connect.WithClientOptions(opts...),
		),
		listSvcSvcRules: connect.NewClient[netguard.ListSvcSvcRulesReq, netguard.ListSvcSvcRulesResp](
			httpClient,
			baseURL+NetguardServiceListSvcSvcRulesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListSvcSvcRules")),
			connect.WithClientOptions(opts...),
		),
		getSvcSvcRule: connect.NewClient[netguard.GetSvcSvcRuleReq, netguard.GetSvcSvcRuleResp](
			httpClient,
			baseURL+NetguardServiceGetSvcSvcRuleProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetSvcSvcRule")),
			connect.WithClientOptions(opts...),
		),
		listSvcFqdnRules: connect.NewClient[netguard.ListSvcFqdnRulesReq, netguard.ListSvcFqdnRulesResp](
			httpClient,
			baseURL+NetguardServiceListSvcFqdnRulesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListSvcFqdnRules")),
			connect.WithClientOptions(opts...),
		),
		getSvcFqdnRule: connect.NewClient[netguard.GetSvcFqdnRuleReq, netguard.GetSvcFqdnRuleResp](
			httpClient,
			baseURL+NetguardServiceGetSvcFqdnRuleProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetSvcFqdnRule")),
			connect.WithClientOptions(opts...),
		),
		listIECidrSvcRules: connect.NewClient[netguard.ListIECidrSvcRulesReq, netguard.ListIECidrSvcRulesResp](
			httpClient,
			baseURL+NetguardServiceListIECidrSvcRulesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("ListIECidrSvcRules")),
			connect.WithClientOptions(opts...),
		),
		getIECidrSvcRule: connect.NewClient[netguard.GetIECidrSvcRuleReq, netguard.GetIECidrSvcRuleResp](
			httpClient,
			baseURL+NetguardServiceGetIECidrSvcRuleProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("GetIECidrSvcRule")),
			connect.WithClientOptions(opts...),
		),
		watchServices: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchServicesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchServices")),
			connect.WithClientOptions(opts...),
		),
		watchAddressGroups: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchAddressGroupsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroups")),
			connect.WithClientOptions(opts...),
		),
		watchAddressGroupBindings: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchAddressGroupBindingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroupBindings")),
			connect.WithClientOptions(opts...),
		),
		watchAddressGroupPortMappings: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchAddressGroupPortMappingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroupPortMappings")),
			connect.WithClientOptions(opts...),
		),
		watchAddressGroupBindingPolicies: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchAddressGroupBindingPoliciesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroupBindingPolicies")),
			connect.WithClientOptions(opts...),
		),
		watchHosts: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchHostsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchHosts")),
			connect.WithClientOptions(opts...),
		),
		watchHostBindings: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchHostBindingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchHostBindings")),
			connect.WithClientOptions(opts...),
		),
		watchNetworks: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchNetworksProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchNetworks")),
			connect.WithClientOptions(opts...),
		),
		watchNetworkBindings: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchNetworkBindingsProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchNetworkBindings")),
			connect.WithClientOptions(opts...),
		),
		watchSvcSvcRules: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchSvcSvcRulesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchSvcSvcRules")),
			connect.WithClientOptions(opts...),
		),
		watchSvcFqdnRules: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchSvcFqdnRulesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchSvcFqdnRules")),
			connect.WithClientOptions(opts...),
		),
		watchIECidrSvcRules: connect.NewClient[netguard.WatchRequest, netguard.WatchEvent](
			httpClient,
			baseURL+NetguardServiceWatchIECidrSvcRulesProcedure,
			connect.WithSchema(netguardServiceMethods.ByName("WatchIECidrSvcRules")),
			connect.WithClientOptions(opts...),
		),
	}
}

// netguardServiceClient implements NetguardServiceClient.
type netguardServiceClient struct {
	sync                             *connect.Client[netguard.SyncReq, emptypb.Empty]
	syncStatus                       *connect.Client[emptypb.Empty, netguard.SyncStatusResp]
	markForDeletion                  *connect.Client[netguard.MarkForDeletionReq, emptypb.Empty]
	listServices                     *connect.Client[netguard.ListServicesReq, netguard.ListServicesResp]
	getService                       *connect.Client[netguard.GetServiceReq, netguard.GetServiceResp]
	listAddressGroups                *connect.Client[netguard.ListAddressGroupsReq, netguard.ListAddressGroupsResp]
	getAddressGroup                  *connect.Client[netguard.GetAddressGroupReq, netguard.GetAddressGroupResp]
	listAddressGroupBindings         *connect.Client[netguard.ListAddressGroupBindingsReq, netguard.ListAddressGroupBindingsResp]
	getAddressGroupBinding           *connect.Client[netguard.GetAddressGroupBindingReq, netguard.GetAddressGroupBindingResp]
	listAddressGroupPortMappings     *connect.Client[netguard.ListAddressGroupPortMappingsReq, netguard.ListAddressGroupPortMappingsResp]
	getAddressGroupPortMapping       *connect.Client[netguard.GetAddressGroupPortMappingReq, netguard.GetAddressGroupPortMappingResp]
	listAddressGroupBindingPolicies  *connect.Client[netguard.ListAddressGroupBindingPoliciesReq, netguard.ListAddressGroupBindingPoliciesResp]
	getAddressGroupBindingPolicy     *connect.Client[netguard.GetAddressGroupBindingPolicyReq, netguard.GetAddressGroupBindingPolicyResp]
	listHosts                        *connect.Client[netguard.ListHostsReq, netguard.ListHostsResp]
	getHost                          *connect.Client[netguard.GetHostReq, netguard.GetHostResp]
	listHostBindings                 *connect.Client[netguard.ListHostBindingsReq, netguard.ListHostBindingsResp]
	getHostBinding                   *connect.Client[netguard.GetHostBindingReq, netguard.GetHostBindingResp]
	listNetworks                     *connect.Client[netguard.ListNetworksReq, netguard.ListNetworksResp]
	getNetwork                       *connect.Client[netguard.GetNetworkReq, netguard.GetNetworkResp]
	listNetworkBindings              *connect.Client[netguard.ListNetworkBindingsReq, netguard.ListNetworkBindingsResp]
	getNetworkBinding                *connect.Client[netguard.GetNetworkBindingReq, netguard.GetNetworkBindingResp]
	listSvcSvcRules                  *connect.Client[netguard.ListSvcSvcRulesReq, netguard.ListSvcSvcRulesResp]
	getSvcSvcRule                    *connect.Client[netguard.GetSvcSvcRuleReq, netguard.GetSvcSvcRuleResp]
	listSvcFqdnRules                 *connect.Client[netguard.ListSvcFqdnRulesReq, netguard.ListSvcFqdnRulesResp]
	getSvcFqdnRule                   *connect.Client[netguard.GetSvcFqdnRuleReq, netguard.GetSvcFqdnRuleResp]
	listIECidrSvcRules               *connect.Client[netguard.ListIECidrSvcRulesReq, netguard.ListIECidrSvcRulesResp]
	getIECidrSvcRule                 *connect.Client[netguard.GetIECidrSvcRuleReq, netguard.GetIECidrSvcRuleResp]
	watchServices                    *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchAddressGroups               *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchAddressGroupBindings        *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchAddressGroupPortMappings    *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchAddressGroupBindingPolicies *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchHosts                       *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchHostBindings                *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchNetworks                    *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchNetworkBindings             *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchSvcSvcRules                 *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchSvcFqdnRules                *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
	watchIECidrSvcRules              *connect.Client[netguard.WatchRequest, netguard.WatchEvent]
}

// Sync calls netguard.v1.NetguardService.Sync.
func (c *netguardServiceClient) Sync(ctx context.Context, req *connect.Request[netguard.SyncReq]) (*connect.Response[emptypb.Empty], error) {
	return c.sync.CallUnary(ctx, req)
}

// SyncStatus calls netguard.v1.NetguardService.SyncStatus.
func (c *netguardServiceClient) SyncStatus(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[netguard.SyncStatusResp], error) {
	return c.syncStatus.CallUnary(ctx, req)
}

// MarkForDeletion calls netguard.v1.NetguardService.MarkForDeletion.
func (c *netguardServiceClient) MarkForDeletion(ctx context.Context, req *connect.Request[netguard.MarkForDeletionReq]) (*connect.Response[emptypb.Empty], error) {
	return c.markForDeletion.CallUnary(ctx, req)
}

// ListServices calls netguard.v1.NetguardService.ListServices.
func (c *netguardServiceClient) ListServices(ctx context.Context, req *connect.Request[netguard.ListServicesReq]) (*connect.Response[netguard.ListServicesResp], error) {
	return c.listServices.CallUnary(ctx, req)
}

// GetService calls netguard.v1.NetguardService.GetService.
func (c *netguardServiceClient) GetService(ctx context.Context, req *connect.Request[netguard.GetServiceReq]) (*connect.Response[netguard.GetServiceResp], error) {
	return c.getService.CallUnary(ctx, req)
}

// ListAddressGroups calls netguard.v1.NetguardService.ListAddressGroups.
func (c *netguardServiceClient) ListAddressGroups(ctx context.Context, req *connect.Request[netguard.ListAddressGroupsReq]) (*connect.Response[netguard.ListAddressGroupsResp], error) {
	return c.listAddressGroups.CallUnary(ctx, req)
}

// GetAddressGroup calls netguard.v1.NetguardService.GetAddressGroup.
func (c *netguardServiceClient) GetAddressGroup(ctx context.Context, req *connect.Request[netguard.GetAddressGroupReq]) (*connect.Response[netguard.GetAddressGroupResp], error) {
	return c.getAddressGroup.CallUnary(ctx, req)
}

// ListAddressGroupBindings calls netguard.v1.NetguardService.ListAddressGroupBindings.
func (c *netguardServiceClient) ListAddressGroupBindings(ctx context.Context, req *connect.Request[netguard.ListAddressGroupBindingsReq]) (*connect.Response[netguard.ListAddressGroupBindingsResp], error) {
	return c.listAddressGroupBindings.CallUnary(ctx, req)
}

// GetAddressGroupBinding calls netguard.v1.NetguardService.GetAddressGroupBinding.
func (c *netguardServiceClient) GetAddressGroupBinding(ctx context.Context, req *connect.Request[netguard.GetAddressGroupBindingReq]) (*connect.Response[netguard.GetAddressGroupBindingResp], error) {
	return c.getAddressGroupBinding.CallUnary(ctx, req)
}

// ListAddressGroupPortMappings calls netguard.v1.NetguardService.ListAddressGroupPortMappings.
func (c *netguardServiceClient) ListAddressGroupPortMappings(ctx context.Context, req *connect.Request[netguard.ListAddressGroupPortMappingsReq]) (*connect.Response[netguard.ListAddressGroupPortMappingsResp], error) {
	return c.listAddressGroupPortMappings.CallUnary(ctx, req)
}

// GetAddressGroupPortMapping calls netguard.v1.NetguardService.GetAddressGroupPortMapping.
func (c *netguardServiceClient) GetAddressGroupPortMapping(ctx context.Context, req *connect.Request[netguard.GetAddressGroupPortMappingReq]) (*connect.Response[netguard.GetAddressGroupPortMappingResp], error) {
	return c.getAddressGroupPortMapping.CallUnary(ctx, req)
}

// ListAddressGroupBindingPolicies calls
// netguard.v1.NetguardService.ListAddressGroupBindingPolicies.
func (c *netguardServiceClient) ListAddressGroupBindingPolicies(ctx context.Context, req *connect.Request[netguard.ListAddressGroupBindingPoliciesReq]) (*connect.Response[netguard.ListAddressGroupBindingPoliciesResp], error) {
	return c.listAddressGroupBindingPolicies.CallUnary(ctx, req)
}

// GetAddressGroupBindingPolicy calls netguard.v1.NetguardService.GetAddressGroupBindingPolicy.
func (c *netguardServiceClient) GetAddressGroupBindingPolicy(ctx context.Context, req *connect.Request[netguard.GetAddressGroupBindingPolicyReq]) (*connect.Response[netguard.GetAddressGroupBindingPolicyResp], error) {
	return c.getAddressGroupBindingPolicy.CallUnary(ctx, req)
}

// ListHosts calls netguard.v1.NetguardService.ListHosts.
func (c *netguardServiceClient) ListHosts(ctx context.Context, req *connect.Request[netguard.ListHostsReq]) (*connect.Response[netguard.ListHostsResp], error) {
	return c.listHosts.CallUnary(ctx, req)
}

// GetHost calls netguard.v1.NetguardService.GetHost.
func (c *netguardServiceClient) GetHost(ctx context.Context, req *connect.Request[netguard.GetHostReq]) (*connect.Response[netguard.GetHostResp], error) {
	return c.getHost.CallUnary(ctx, req)
}

// ListHostBindings calls netguard.v1.NetguardService.ListHostBindings.
func (c *netguardServiceClient) ListHostBindings(ctx context.Context, req *connect.Request[netguard.ListHostBindingsReq]) (*connect.Response[netguard.ListHostBindingsResp], error) {
	return c.listHostBindings.CallUnary(ctx, req)
}

// GetHostBinding calls netguard.v1.NetguardService.GetHostBinding.
func (c *netguardServiceClient) GetHostBinding(ctx context.Context, req *connect.Request[netguard.GetHostBindingReq]) (*connect.Response[netguard.GetHostBindingResp], error) {
	return c.getHostBinding.CallUnary(ctx, req)
}

// ListNetworks calls netguard.v1.NetguardService.ListNetworks.
func (c *netguardServiceClient) ListNetworks(ctx context.Context, req *connect.Request[netguard.ListNetworksReq]) (*connect.Response[netguard.ListNetworksResp], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// GetNetwork calls netguard.v1.NetguardService.GetNetwork.
func (c *netguardServiceClient) GetNetwork(ctx context.Context, req *connect.Request[netguard.GetNetworkReq]) (*connect.Response[netguard.GetNetworkResp], error) {
	return c.getNetwork.CallUnary(ctx, req)
}

// ListNetworkBindings calls netguard.v1.NetguardService.ListNetworkBindings.
func (c *netguardServiceClient) ListNetworkBindings(ctx context.Context, req *connect.Request[netguard.ListNetworkBindingsReq]) (*connect.Response[netguard.ListNetworkBindingsResp], error) {
	return c.listNetworkBindings.CallUnary(ctx, req)
}

// GetNetworkBinding calls netguard.v1.NetguardService.GetNetworkBinding.
func (c *netguardServiceClient) GetNetworkBinding(ctx context.Context, req *connect.Request[netguard.GetNetworkBindingReq]) (*connect.Response[netguard.GetNetworkBindingResp], error) {
	return c.getNetworkBinding.CallUnary(ctx, req)
}

// ListSvcSvcRules calls netguard.v1.NetguardService.ListSvcSvcRules.
func (c *netguardServiceClient) ListSvcSvcRules(ctx context.Context, req *connect.Request[netguard.ListSvcSvcRulesReq]) (*connect.Response[netguard.ListSvcSvcRulesResp], error) {
	return c.listSvcSvcRules.CallUnary(ctx, req)
}

// GetSvcSvcRule calls netguard.v1.NetguardService.GetSvcSvcRule.
func (c *netguardServiceClient) GetSvcSvcRule(ctx context.Context, req *connect.Request[netguard.GetSvcSvcRuleReq]) (*connect.Response[netguard.GetSvcSvcRuleResp], error) {
	return c.getSvcSvcRule.CallUnary(ctx, req)
}

// ListSvcFqdnRules calls netguard.v1.NetguardService.ListSvcFqdnRules.
func (c *netguardServiceClient) ListSvcFqdnRules(ctx context.Context, req *connect.Request[netguard.ListSvcFqdnRulesReq]) (*connect.Response[netguard.ListSvcFqdnRulesResp], error) {
	return c.listSvcFqdnRules.CallUnary(ctx, req)
}

// GetSvcFqdnRule calls netguard.v1.NetguardService.GetSvcFqdnRule.
func (c *netguardServiceClient) GetSvcFqdnRule(ctx context.Context, req *connect.Request[netguard.GetSvcFqdnRuleReq]) (*connect.Response[netguard.GetSvcFqdnRuleResp], error) {
	return c.getSvcFqdnRule.CallUnary(ctx, req)
}

// ListIECidrSvcRules calls netguard.v1.NetguardService.ListIECidrSvcRules.
func (c *netguardServiceClient) ListIECidrSvcRules(ctx context.Context, req *connect.Request[netguard.ListIECidrSvcRulesReq]) (*connect.Response[netguard.ListIECidrSvcRulesResp], error) {
	return c.listIECidrSvcRules.CallUnary(ctx, req)
}

// GetIECidrSvcRule calls netguard.v1.NetguardService.GetIECidrSvcRule.
func (c *netguardServiceClient) GetIECidrSvcRule(ctx context.Context, req *connect.Request[netguard.GetIECidrSvcRuleReq]) (*connect.Response[netguard.GetIECidrSvcRuleResp], error) {
	return c.getIECidrSvcRule.CallUnary(ctx, req)
}

// WatchServices calls netguard.v1.NetguardService.WatchServices.
func (c *netguardServiceClient) WatchServices(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchServices.CallServerStream(ctx, req)
}

// WatchAddressGroups calls netguard.v1.NetguardService.WatchAddressGroups.
func (c *netguardServiceClient) WatchAddressGroups(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchAddressGroups.CallServerStream(ctx, req)
}

// WatchAddressGroupBindings calls netguard.v1.NetguardService.WatchAddressGroupBindings.
func (c *netguardServiceClient) WatchAddressGroupBindings(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchAddressGroupBindings.CallServerStream(ctx, req)
}

// WatchAddressGroupPortMappings calls netguard.v1.NetguardService.WatchAddressGroupPortMappings.
func (c *netguardServiceClient) WatchAddressGroupPortMappings(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchAddressGroupPortMappings.CallServerStream(ctx, req)
}

// WatchAddressGroupBindingPolicies calls
// netguard.v1.NetguardService.WatchAddressGroupBindingPolicies.
func (c *netguardServiceClient) WatchAddressGroupBindingPolicies(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchAddressGroupBindingPolicies.CallServerStream(ctx, req)
}

// WatchHosts calls netguard.v1.NetguardService.WatchHosts.
func (c *netguardServiceClient) WatchHosts(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchHosts.CallServerStream(ctx, req)
}

// WatchHostBindings calls netguard.v1.NetguardService.WatchHostBindings.
func (c *netguardServiceClient) WatchHostBindings(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchHostBindings.CallServerStream(ctx, req)
}

// WatchNetworks calls netguard.v1.NetguardService.WatchNetworks.
func (c *netguardServiceClient) WatchNetworks(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchNetworks.CallServerStream(ctx, req)
}

// WatchNetworkBindings calls netguard.v1.NetguardService.WatchNetworkBindings.
func (c *netguardServiceClient) WatchNetworkBindings(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchNetworkBindings.CallServerStream(ctx, req)
}

// WatchSvcSvcRules calls netguard.v1.NetguardService.WatchSvcSvcRules.
func (c *netguardServiceClient) WatchSvcSvcRules(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchSvcSvcRules.CallServerStream(ctx, req)
}

// WatchSvcFqdnRules calls netguard.v1.NetguardService.WatchSvcFqdnRules.
func (c *netguardServiceClient) WatchSvcFqdnRules(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchSvcFqdnRules.CallServerStream(ctx, req)
}

// WatchIECidrSvcRules calls netguard.v1.NetguardService.WatchIECidrSvcRules.
func (c *netguardServiceClient) WatchIECidrSvcRules(ctx context.Context, req *connect.Request[netguard.WatchRequest]) (*connect.ServerStreamForClient[netguard.WatchEvent], error) {
	return c.watchIECidrSvcRules.CallServerStream(ctx, req)
}

// NetguardServiceHandler is an implementation of the netguard.v1.NetguardService service.
type NetguardServiceHandler interface {
	Sync(context.Context, *connect.Request[netguard.SyncReq]) (*connect.Response[emptypb.Empty], error)
	SyncStatus(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[netguard.SyncStatusResp], error)
	MarkForDeletion(context.Context, *connect.Request[netguard.MarkForDeletionReq]) (*connect.Response[emptypb.Empty], error)
	ListServices(context.Context, *connect.Request[netguard.ListServicesReq]) (*connect.Response[netguard.ListServicesResp], error)
	GetService(context.Context, *connect.Request[netguard.GetServiceReq]) (*connect.Response[netguard.GetServiceResp], error)
	ListAddressGroups(context.Context, *connect.Request[netguard.ListAddressGroupsReq]) (*connect.Response[netguard.ListAddressGroupsResp], error)
	GetAddressGroup(context.Context, *connect.Request[netguard.GetAddressGroupReq]) (*connect.Response[netguard.GetAddressGroupResp], error)
	ListAddressGroupBindings(context.Context, *connect.Request[netguard.ListAddressGroupBindingsReq]) (*connect.Response[netguard.ListAddressGroupBindingsResp], error)
	GetAddressGroupBinding(context.Context, *connect.Request[netguard.GetAddressGroupBindingReq]) (*connect.Response[netguard.GetAddressGroupBindingResp], error)
	ListAddressGroupPortMappings(context.Context, *connect.Request[netguard.ListAddressGroupPortMappingsReq]) (*connect.Response[netguard.ListAddressGroupPortMappingsResp], error)
	GetAddressGroupPortMapping(context.Context, *connect.Request[netguard.GetAddressGroupPortMappingReq]) (*connect.Response[netguard.GetAddressGroupPortMappingResp], error)
	ListAddressGroupBindingPolicies(context.Context, *connect.Request[netguard.ListAddressGroupBindingPoliciesReq]) (*connect.Response[netguard.ListAddressGroupBindingPoliciesResp], error)
	GetAddressGroupBindingPolicy(context.Context, *connect.Request[netguard.GetAddressGroupBindingPolicyReq]) (*connect.Response[netguard.GetAddressGroupBindingPolicyResp], error)
	ListHosts(context.Context, *connect.Request[netguard.ListHostsReq]) (*connect.Response[netguard.ListHostsResp], error)
	GetHost(context.Context, *connect.Request[netguard.GetHostReq]) (*connect.Response[netguard.GetHostResp], error)
	ListHostBindings(context.Context, *connect.Request[netguard.ListHostBindingsReq]) (*connect.Response[netguard.ListHostBindingsResp], error)
	GetHostBinding(context.Context, *connect.Request[netguard.GetHostBindingReq]) (*connect.Response[netguard.GetHostBindingResp], error)
	ListNetworks(context.Context, *connect.Request[netguard.ListNetworksReq]) (*connect.Response[netguard.ListNetworksResp], error)
	GetNetwork(context.Context, *connect.Request[netguard.GetNetworkReq]) (*connect.Response[netguard.GetNetworkResp], error)
	ListNetworkBindings(context.Context, *connect.Request[netguard.ListNetworkBindingsReq]) (*connect.Response[netguard.ListNetworkBindingsResp], error)
	GetNetworkBinding(context.Context, *connect.Request[netguard.GetNetworkBindingReq]) (*connect.Response[netguard.GetNetworkBindingResp], error)
	ListSvcSvcRules(context.Context, *connect.Request[netguard.ListSvcSvcRulesReq]) (*connect.Response[netguard.ListSvcSvcRulesResp], error)
	GetSvcSvcRule(context.Context, *connect.Request[netguard.GetSvcSvcRuleReq]) (*connect.Response[netguard.GetSvcSvcRuleResp], error)
	ListSvcFqdnRules(context.Context, *connect.Request[netguard.ListSvcFqdnRulesReq]) (*connect.Response[netguard.ListSvcFqdnRulesResp], error)
	GetSvcFqdnRule(context.Context, *connect.Request[netguard.GetSvcFqdnRuleReq]) (*connect.Response[netguard.GetSvcFqdnRuleResp], error)
	ListIECidrSvcRules(context.Context, *connect.Request[netguard.ListIECidrSvcRulesReq]) (*connect.Response[netguard.ListIECidrSvcRulesResp], error)
	GetIECidrSvcRule(context.Context, *connect.Request[netguard.GetIECidrSvcRuleReq]) (*connect.Response[netguard.GetIECidrSvcRuleResp], error)
	WatchServices(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchAddressGroups(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchAddressGroupBindings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchAddressGroupPortMappings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchAddressGroupBindingPolicies(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchHosts(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchHostBindings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchNetworks(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchNetworkBindings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchSvcSvcRules(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchSvcFqdnRules(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
	WatchIECidrSvcRules(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error
}

// NewNetguardServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNetguardServiceHandler(svc NetguardServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	netguardServiceMethods := netguard.File_netguard_service_proto.Services().ByName("NetguardService").Methods()
	netguardServiceSyncHandler := connect.NewUnaryHandler(
		NetguardServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(netguardServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceSyncStatusHandler := connect.NewUnaryHandler(
		NetguardServiceSyncStatusProcedure,
		svc.SyncStatus,
		connect.WithSchema(netguardServiceMethods.ByName("SyncStatus")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceMarkForDeletionHandler := connect.NewUnaryHandler(
		NetguardServiceMarkForDeletionProcedure,
		svc.MarkForDeletion,
		connect.WithSchema(netguardServiceMethods.ByName("MarkForDeletion")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListServicesHandler := connect.NewUnaryHandler(
		NetguardServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(netguardServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetServiceHandler := connect.NewUnaryHandler(
		NetguardServiceGetServiceProcedure,
		svc.GetService,
		connect.WithSchema(netguardServiceMethods.ByName("GetService")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListAddressGroupsHandler := connect.NewUnaryHandler(
		NetguardServiceListAddressGroupsProcedure,
		svc.ListAddressGroups,
		connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroups")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetAddressGroupHandler := connect.NewUnaryHandler(
		NetguardServiceGetAddressGroupProcedure,
		svc.GetAddressGroup,
		connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroup")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListAddressGroupBindingsHandler := connect.NewUnaryHandler(
		NetguardServiceListAddressGroupBindingsProcedure,
		svc.ListAddressGroupBindings,
		connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroupBindings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetAddressGroupBindingHandler := connect.NewUnaryHandler(
		NetguardServiceGetAddressGroupBindingProcedure,
		svc.GetAddressGroupBinding,
		connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroupBinding")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListAddressGroupPortMappingsHandler := connect.NewUnaryHandler(
		NetguardServiceListAddressGroupPortMappingsProcedure,
		svc.ListAddressGroupPortMappings,
		connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroupPortMappings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetAddressGroupPortMappingHandler := connect.NewUnaryHandler(
		NetguardServiceGetAddressGroupPortMappingProcedure,
		svc.GetAddressGroupPortMapping,
		connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroupPortMapping")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListAddressGroupBindingPoliciesHandler := connect.NewUnaryHandler(
		NetguardServiceListAddressGroupBindingPoliciesProcedure,
		svc.ListAddressGroupBindingPolicies,
		connect.WithSchema(netguardServiceMethods.ByName("ListAddressGroupBindingPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetAddressGroupBindingPolicyHandler := connect.NewUnaryHandler(
		NetguardServiceGetAddressGroupBindingPolicyProcedure,
		svc.GetAddressGroupBindingPolicy,
		connect.WithSchema(netguardServiceMethods.ByName("GetAddressGroupBindingPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListHostsHandler := connect.NewUnaryHandler(
		NetguardServiceListHostsProcedure,
		svc.ListHosts,
		connect.WithSchema(netguardServiceMethods.ByName("ListHosts")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetHostHandler := connect.NewUnaryHandler(
		NetguardServiceGetHostProcedure,
		svc.GetHost,
		connect.WithSchema(netguardServiceMethods.ByName("GetHost")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListHostBindingsHandler := connect.NewUnaryHandler(
		NetguardServiceListHostBindingsProcedure,
		svc.ListHostBindings,
		connect.WithSchema(netguardServiceMethods.ByName("ListHostBindings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetHostBindingHandler := connect.NewUnaryHandler(
		NetguardServiceGetHostBindingProcedure,
		svc.GetHostBinding,
		connect.WithSchema(netguardServiceMethods.ByName("GetHostBinding")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListNetworksHandler := connect.NewUnaryHandler(
		NetguardServiceListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(netguardServiceMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetNetworkHandler := connect.NewUnaryHandler(
		NetguardServiceGetNetworkProcedure,
		svc.GetNetwork,
		connect.WithSchema(netguardServiceMethods.ByName("GetNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListNetworkBindingsHandler := connect.NewUnaryHandler(
		NetguardServiceListNetworkBindingsProcedure,
		svc.ListNetworkBindings,
		connect.WithSchema(netguardServiceMethods.ByName("ListNetworkBindings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetNetworkBindingHandler := connect.NewUnaryHandler(
		NetguardServiceGetNetworkBindingProcedure,
		svc.GetNetworkBinding,
		connect.WithSchema(netguardServiceMethods.ByName("GetNetworkBinding")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListSvcSvcRulesHandler := connect.NewUnaryHandler(
		NetguardServiceListSvcSvcRulesProcedure,
		svc.ListSvcSvcRules,
		connect.WithSchema(netguardServiceMethods.ByName("ListSvcSvcRules")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetSvcSvcRuleHandler := connect.NewUnaryHandler(
		NetguardServiceGetSvcSvcRuleProcedure,
		svc.GetSvcSvcRule,
		connect.WithSchema(netguardServiceMethods.ByName("GetSvcSvcRule")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListSvcFqdnRulesHandler := connect.NewUnaryHandler(
		NetguardServiceListSvcFqdnRulesProcedure,
		svc.ListSvcFqdnRules,
		connect.WithSchema(netguardServiceMethods.ByName("ListSvcFqdnRules")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetSvcFqdnRuleHandler := connect.NewUnaryHandler(
		NetguardServiceGetSvcFqdnRuleProcedure,
		svc.GetSvcFqdnRule,
		connect.WithSchema(netguardServiceMethods.ByName("GetSvcFqdnRule")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceListIECidrSvcRulesHandler := connect.NewUnaryHandler(
		NetguardServiceListIECidrSvcRulesProcedure,
		svc.ListIECidrSvcRules,
		connect.WithSchema(netguardServiceMethods.ByName("ListIECidrSvcRules")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceGetIECidrSvcRuleHandler := connect.NewUnaryHandler(
		NetguardServiceGetIECidrSvcRuleProcedure,
		svc.GetIECidrSvcRule,
		connect.WithSchema(netguardServiceMethods.ByName("GetIECidrSvcRule")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchServicesHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchServicesProcedure,
		svc.WatchServices,
		connect.WithSchema(netguardServiceMethods.ByName("WatchServices")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchAddressGroupsHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchAddressGroupsProcedure,
		svc.WatchAddressGroups,
		connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroups")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchAddressGroupBindingsHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchAddressGroupBindingsProcedure,
		svc.WatchAddressGroupBindings,
		connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroupBindings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchAddressGroupPortMappingsHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchAddressGroupPortMappingsProcedure,
		svc.WatchAddressGroupPortMappings,
		connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroupPortMappings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchAddressGroupBindingPoliciesHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchAddressGroupBindingPoliciesProcedure,
		svc.WatchAddressGroupBindingPolicies,
		connect.WithSchema(netguardServiceMethods.ByName("WatchAddressGroupBindingPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchHostsHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchHostsProcedure,
		svc.WatchHosts,
		connect.WithSchema(netguardServiceMethods.ByName("WatchHosts")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchHostBindingsHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchHostBindingsProcedure,
		svc.WatchHostBindings,
		connect.WithSchema(netguardServiceMethods.ByName("WatchHostBindings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchNetworksHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchNetworksProcedure,
		svc.WatchNetworks,
		connect.WithSchema(netguardServiceMethods.ByName("WatchNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchNetworkBindingsHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchNetworkBindingsProcedure,
		svc.WatchNetworkBindings,
		connect.WithSchema(netguardServiceMethods.ByName("WatchNetworkBindings")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchSvcSvcRulesHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchSvcSvcRulesProcedure,
		svc.WatchSvcSvcRules,
		connect.WithSchema(netguardServiceMethods.ByName("WatchSvcSvcRules")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchSvcFqdnRulesHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchSvcFqdnRulesProcedure,
		svc.WatchSvcFqdnRules,
		connect.WithSchema(netguardServiceMethods.ByName("WatchSvcFqdnRules")),
		connect.WithHandlerOptions(opts...),
	)
	netguardServiceWatchIECidrSvcRulesHandler := connect.NewServerStreamHandler(
		NetguardServiceWatchIECidrSvcRulesProcedure,
		svc.WatchIECidrSvcRules,
		connect.WithSchema(netguardServiceMethods.ByName("WatchIECidrSvcRules")),
		connect.WithHandlerOptions(opts...),
	)
	return "/netguard.v1.NetguardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NetguardServiceSyncProcedure:
			netguardServiceSyncHandler.ServeHTTP(w, r)
		case NetguardServiceSyncStatusProcedure:
			netguardServiceSyncStatusHandler.ServeHTTP(w, r)
		case NetguardServiceMarkForDeletionProcedure:
			netguardServiceMarkForDeletionHandler.ServeHTTP(w, r)
		case NetguardServiceListServicesProcedure:
			netguardServiceListServicesHandler.ServeHTTP(w, r)
		case NetguardServiceGetServiceProcedure:
			netguardServiceGetServiceHandler.ServeHTTP(w, r)
		case NetguardServiceListAddressGroupsProcedure:
			netguardServiceListAddressGroupsHandler.ServeHTTP(w, r)
		case NetguardServiceGetAddressGroupProcedure:
			netguardServiceGetAddressGroupHandler.ServeHTTP(w, r)
		case NetguardServiceListAddressGroupBindingsProcedure:
			netguardServiceListAddressGroupBindingsHandler.ServeHTTP(w, r)
		case NetguardServiceGetAddressGroupBindingProcedure:
			netguardServiceGetAddressGroupBindingHandler.ServeHTTP(w, r)
		case NetguardServiceListAddressGroupPortMappingsProcedure:
			netguardServiceListAddressGroupPortMappingsHandler.ServeHTTP(w, r)
		case NetguardServiceGetAddressGroupPortMappingProcedure:
			netguardServiceGetAddressGroupPortMappingHandler.ServeHTTP(w, r)
		case NetguardServiceListAddressGroupBindingPoliciesProcedure:
			netguardServiceListAddressGroupBindingPoliciesHandler.ServeHTTP(w, r)
		case NetguardServiceGetAddressGroupBindingPolicyProcedure:
			netguardServiceGetAddressGroupBindingPolicyHandler.ServeHTTP(w, r)
		case NetguardServiceListHostsProcedure:
			netguardServiceListHostsHandler.ServeHTTP(w, r)
		case NetguardServiceGetHostProcedure:
			netguardServiceGetHostHandler.ServeHTTP(w, r)
		case NetguardServiceListHostBindingsProcedure:
			netguardServiceListHostBindingsHandler.ServeHTTP(w, r)
		case NetguardServiceGetHostBindingProcedure:
			netguardServiceGetHostBindingHandler.ServeHTTP(w, r)
		case NetguardServiceListNetworksProcedure:
			netguardServiceListNetworksHandler.ServeHTTP(w, r)
		case NetguardServiceGetNetworkProcedure:
			netguardServiceGetNetworkHandler.ServeHTTP(w, r)
		case NetguardServiceListNetworkBindingsProcedure:
			netguardServiceListNetworkBindingsHandler.ServeHTTP(w, r)
		case NetguardServiceGetNetworkBindingProcedure:
			netguardServiceGetNetworkBindingHandler.ServeHTTP(w, r)
		case NetguardServiceListSvcSvcRulesProcedure:
			netguardServiceListSvcSvcRulesHandler.ServeHTTP(w, r)
		case NetguardServiceGetSvcSvcRuleProcedure:
			netguardServiceGetSvcSvcRuleHandler.ServeHTTP(w, r)
		case NetguardServiceListSvcFqdnRulesProcedure:
			netguardServiceListSvcFqdnRulesHandler.ServeHTTP(w, r)
		case NetguardServiceGetSvcFqdnRuleProcedure:
			netguardServiceGetSvcFqdnRuleHandler.ServeHTTP(w, r)
		case NetguardServiceListIECidrSvcRulesProcedure:
			netguardServiceListIECidrSvcRulesHandler.ServeHTTP(w, r)
		case NetguardServiceGetIECidrSvcRuleProcedure:
			netguardServiceGetIECidrSvcRuleHandler.ServeHTTP(w, r)
		case NetguardServiceWatchServicesProcedure:
			netguardServiceWatchServicesHandler.ServeHTTP(w, r)
		case NetguardServiceWatchAddressGroupsProcedure:
			netguardServiceWatchAddressGroupsHandler.ServeHTTP(w, r)
		case NetguardServiceWatchAddressGroupBindingsProcedure:
			netguardServiceWatchAddressGroupBindingsHandler.ServeHTTP(w, r)
		case NetguardServiceWatchAddressGroupPortMappingsProcedure:
			netguardServiceWatchAddressGroupPortMappingsHandler.ServeHTTP(w, r)
		case NetguardServiceWatchAddressGroupBindingPoliciesProcedure:
			netguardServiceWatchAddressGroupBindingPoliciesHandler.ServeHTTP(w, r)
		case NetguardServiceWatchHostsProcedure:
			netguardServiceWatchHostsHandler.ServeHTTP(w, r)
		case NetguardServiceWatchHostBindingsProcedure:
			netguardServiceWatchHostBindingsHandler.ServeHTTP(w, r)
		case NetguardServiceWatchNetworksProcedure:
			netguardServiceWatchNetworksHandler.ServeHTTP(w, r)
		case NetguardServiceWatchNetworkBindingsProcedure:
			netguardServiceWatchNetworkBindingsHandler.ServeHTTP(w, r)
		case NetguardServiceWatchSvcSvcRulesProcedure:
			netguardServiceWatchSvcSvcRulesHandler.ServeHTTP(w, r)
		case NetguardServiceWatchSvcFqdnRulesProcedure:
			netguardServiceWatchSvcFqdnRulesHandler.ServeHTTP(w, r)
		case NetguardServiceWatchIECidrSvcRulesProcedure:
			netguardServiceWatchIECidrSvcRulesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNetguardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNetguardServiceHandler struct{}

func (UnimplementedNetguardServiceHandler) Sync(context.Context, *connect.Request[netguard.SyncReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.Sync is not implemented"))
}

func (UnimplementedNetguardServiceHandler) SyncStatus(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[netguard.SyncStatusResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.SyncStatus is not implemented"))
}

func (UnimplementedNetguardServiceHandler) MarkForDeletion(context.Context, *connect.Request[netguard.MarkForDeletionReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.MarkForDeletion is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListServices(context.Context, *connect.Request[netguard.ListServicesReq]) (*connect.Response[netguard.ListServicesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListServices is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetService(context.Context, *connect.Request[netguard.GetServiceReq]) (*connect.Response[netguard.GetServiceResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetService is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListAddressGroups(context.Context, *connect.Request[netguard.ListAddressGroupsReq]) (*connect.Response[netguard.ListAddressGroupsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListAddressGroups is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetAddressGroup(context.Context, *connect.Request[netguard.GetAddressGroupReq]) (*connect.Response[netguard.GetAddressGroupResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetAddressGroup is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListAddressGroupBindings(context.Context, *connect.Request[netguard.ListAddressGroupBindingsReq]) (*connect.Response[netguard.ListAddressGroupBindingsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListAddressGroupBindings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetAddressGroupBinding(context.Context, *connect.Request[netguard.GetAddressGroupBindingReq]) (*connect.Response[netguard.GetAddressGroupBindingResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetAddressGroupBinding is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListAddressGroupPortMappings(context.Context, *connect.Request[netguard.ListAddressGroupPortMappingsReq]) (*connect.Response[netguard.ListAddressGroupPortMappingsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListAddressGroupPortMappings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetAddressGroupPortMapping(context.Context, *connect.Request[netguard.GetAddressGroupPortMappingReq]) (*connect.Response[netguard.GetAddressGroupPortMappingResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetAddressGroupPortMapping is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListAddressGroupBindingPolicies(context.Context, *connect.Request[netguard.ListAddressGroupBindingPoliciesReq]) (*connect.Response[netguard.ListAddressGroupBindingPoliciesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListAddressGroupBindingPolicies is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetAddressGroupBindingPolicy(context.Context, *connect.Request[netguard.GetAddressGroupBindingPolicyReq]) (*connect.Response[netguard.GetAddressGroupBindingPolicyResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetAddressGroupBindingPolicy is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListHosts(context.Context, *connect.Request[netguard.ListHostsReq]) (*connect.Response[netguard.ListHostsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListHosts is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetHost(context.Context, *connect.Request[netguard.GetHostReq]) (*connect.Response[netguard.GetHostResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetHost is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListHostBindings(context.Context, *connect.Request[netguard.ListHostBindingsReq]) (*connect.Response[netguard.ListHostBindingsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListHostBindings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetHostBinding(context.Context, *connect.Request[netguard.GetHostBindingReq]) (*connect.Response[netguard.GetHostBindingResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetHostBinding is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListNetworks(context.Context, *connect.Request[netguard.ListNetworksReq]) (*connect.Response[netguard.ListNetworksResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListNetworks is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetNetwork(context.Context, *connect.Request[netguard.GetNetworkReq]) (*connect.Response[netguard.GetNetworkResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetNetwork is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListNetworkBindings(context.Context, *connect.Request[netguard.ListNetworkBindingsReq]) (*connect.Response[netguard.ListNetworkBindingsResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListNetworkBindings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetNetworkBinding(context.Context, *connect.Request[netguard.GetNetworkBindingReq]) (*connect.Response[netguard.GetNetworkBindingResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetNetworkBinding is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListSvcSvcRules(context.Context, *connect.Request[netguard.ListSvcSvcRulesReq]) (*connect.Response[netguard.ListSvcSvcRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListSvcSvcRules is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetSvcSvcRule(context.Context, *connect.Request[netguard.GetSvcSvcRuleReq]) (*connect.Response[netguard.GetSvcSvcRuleResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetSvcSvcRule is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListSvcFqdnRules(context.Context, *connect.Request[netguard.ListSvcFqdnRulesReq]) (*connect.Response[netguard.ListSvcFqdnRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListSvcFqdnRules is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetSvcFqdnRule(context.Context, *connect.Request[netguard.GetSvcFqdnRuleReq]) (*connect.Response[netguard.GetSvcFqdnRuleResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetSvcFqdnRule is not implemented"))
}

func (UnimplementedNetguardServiceHandler) ListIECidrSvcRules(context.Context, *connect.Request[netguard.ListIECidrSvcRulesReq]) (*connect.Response[netguard.ListIECidrSvcRulesResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.ListIECidrSvcRules is not implemented"))
}

func (UnimplementedNetguardServiceHandler) GetIECidrSvcRule(context.Context, *connect.Request[netguard.GetIECidrSvcRuleReq]) (*connect.Response[netguard.GetIECidrSvcRuleResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.GetIECidrSvcRule is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchServices(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchServices is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchAddressGroups(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchAddressGroups is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchAddressGroupBindings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchAddressGroupBindings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchAddressGroupPortMappings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchAddressGroupPortMappings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchAddressGroupBindingPolicies(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchAddressGroupBindingPolicies is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchHosts(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchHosts is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchHostBindings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchHostBindings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchNetworks(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchNetworks is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchNetworkBindings(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchNetworkBindings is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchSvcSvcRules(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchSvcSvcRules is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchSvcFqdnRules(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchSvcFqdnRules is not implemented"))
}

func (UnimplementedNetguardServiceHandler) WatchIECidrSvcRules(context.Context, *connect.Request[netguard.WatchRequest], *connect.ServerStream[netguard.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netguard.v1.NetguardService.WatchIECidrSvcRules is not implemented"))
}
