---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netguard-environment-debug
  namespace: incloud-sgroups
  labels:
    app.kubernetes.io/name: apiserver
    app.kubernetes.io/instance: netguard
    app.kubernetes.io/component: debug
data:
  # DEBUG: Point to debug backend
  BACKEND_ENDPOINT: netguard-backend-debug:9090

  # Database configuration (same as production)
  DATABASE_CONNECTION_URL: postgres://netguard:netguard@netguard-postgresql.incloud-sgroups.svc:5432/netguard?sslmode=disable
  DATABASE_NAME: netguard
  DATABASE_PASSWORD: netguard
  DATABASE_PORT: "5432"
  DATABASE_SSLMODE: disable
  DATABASE_URL: netguard-postgresql.incloud-sgroups.svc
  DATABASE_USERNAME: netguard
