name: release
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CUSTOM_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CUSTOM_DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create sanitized branch name
        id: sanitize
        run: echo "branch=$(echo ${GITHUB_REF_NAME} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      - name: Build and push apiserver
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.apiserver
          push: true
          tags: ${{ secrets.CUSTOM_DOCKERHUB_USERNAME }}/sgroups.k8s.netguard-apiserver:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ${{ secrets.CUSTOM_DOCKERHUB_USERNAME }}/sgroups.k8s.netguard-backend:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push webhook
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.webhook
          push: true
          tags: ${{ secrets.CUSTOM_DOCKERHUB_USERNAME }}/sgroups.k8s.netguard-webhook:${{ steps.sanitize.outputs.branch }}-${{ steps.short-sha.outputs.sha }}
          platforms: linux/amd64,linux/arm64
