name: test-memdb
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:14
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_USER: postgres
#          POSTGRES_DB: netguard_test
#        ports:
#          - 5432:5432
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

#    - name: Run migrations
#      run: go run cmd/migrate/main.go --pg-uri="postgres://postgres:postgres@localhost:5432/netguard_test?sslmode=disable"

    - name: Run unit tests
      run: go test -v ./internal/domain/...

    - name: Run in-memory repository tests
      run: go test -v ./internal/infrastructure/repositories/mem/...

#    - name: Run PostgreSQL repository tests
#      run: go test -v ./internal/infrastructure/repositories/pg/...
#      env:
#        PG_URI: postgres://postgres:postgres@localhost:5432/netguard_test?sslmode=disable

    - name: Run API tests
      run: go test -v ./internal/api/...

    - name: Run end-to-end tests
      run: go test -v ./internal/app/...